/**
 * Created by cwr.Yingsheng.Feng on 2014.11.23 0023.
 */
Airdroid.UsedLang = {}, Airdroid.Lang.Version = "1.1.0", Airdroid.Lang.Footer = {
    forum: "Forum",
    choose_title: "Choose language",
    nohas_lng: "Not your language?",
    set_lng: "Change",
    language: "Languages",
    Join_translate: "Translate AirDroid to your own language!",
    local_lng: "Installed",
    online_lng: "Available",
    donate: "Donate",
    help: "Help",
    contact: "Contact",
    verficate_code: "passcode",
    about_us: "About us",
    security: "Security",
    privacy_policy: "Privacy policy"
}, Airdroid.Lang.Login = {
    Option_SSL: "Use secured connection (https)",
    Label_Version: "Version: ",
    Message_RetryAfter: "AirDroid passcode is disabled for {0}.",
    Message_NetworkError: "Failed to connect. Please check your network.",
    Message_AutoLoginInProgress: "Auto sign in in progress...",
    Not_LanNetwork: "Failed to connect. Make sure your device is connected to a same WiFi network.",
    Cookies_Required: "Cookies are not enabled on your browser. Please adjust this in your security preferences before continuing.",
    btn_OK: "OK",
    Msg_KickOut: "Your account is signed in elsewhere.{0}You will now be signed out.",
    Tip_KickOut: "If this is not your operation, we recommend that you change password to protect your privacy.",
    Btn_LogInAgain: "Sign in again",
    Button_Login: "Sign in",
    Msg_Srv_Unavailable: "Connection Failed. Troubleshooting guide:",
    Msg_Srv_Unavailable_1: "Check the network of your device",
    Msg_Srv_Unavailable_2: "Unlock or wake up your Android device",
    Message_Connecting: "Connecting to Device...",
    Message_InputPassword: "Please input passcode.",
    Message_Locked: "Locked. Unlock me with your passcode.",
    Message_AlreadyLogin: "Your account is already signed in somewhere else."
}, Airdroid.Lang.Common = {
    Btn_Gotit: "Got it",
    Connecting: "Device not responding.",
    Clear: "Clear",
    ToolTip_Next: "Next[Right Arrow]",
    notify_me_when_find: "Notify me when found",
    present_guest_error: "3. You haven't signed in to this Chromebook using a Google account. Please sign in and try again later.",
    Setting: "Settings",
    Reinstall: "Reinstall",
    Message_Forbidden: "Connection timed out. Please try again.",
    NavBar_ShowDesktop: "Show desktop",
    NavBar_SpeedUpload: "Speed upload",
    NavBar_NewMessage: "New message",
    NavBar_MultipleDesktops: "Multiple desktops",
    ToolTip_SetAsWallpaper: "Set as wallpaper",
    ToolTip_Prev: "Prev[Left Arrow]",
    ToolTip_RotateLeft: "Rotate Left[Up Arrow]",
    ToolTip_RotateRight: "Rotate Right[Down Arrow]",
    Open: "Open",
    NewFolder: "New folder",
    Refresh: "Refresh",
    Paste: "Paste",
    Copy: "Copy",
    Delete: "Delete",
    Export: "Download",
    Install: "Install",
    ZipedAndExport: "Download as ZIP",
    LoadingMore: "Older Threads",
    Server_Stop: "Service stopped by device.",
    Label_SizeColumn: "Size",
    Label_TypeColumn: "Type",
    Label_FormatColumn: "Format",
    Label_ModifyDateColumn: "Date Modified",
    ToolTip_Name: "Name:",
    ToolTip_Time: "Time:",
    ToolTip_Size: "Size:",
    ToolTip_FileLocation: "Location:",
    Tip_ListView: "List view",
    Button_Cancel: "Cancel",
    msg_SameFileName: "Name not changed",
    msg_FileNameIsNull: "A unique name is required.",
    msg_FileNameExist: "Same name exists. Please choose a new one.",
    Msg_AppConfigNotFound: "Failed to locate the configuration file.",
    InputDefaultText_Search: "Search",
    TipText_Call: "Call",
    TipText_Forward: "Forward",
    ToolTip_Share: "Share",
    Continue: "Continue",
    Msg_NotWifiNetWork: "AirDroid is currently using your device's mobile network. To conserve data, please try to connect your device to a WiFi network.",
    Back: "Back",
    Search: "Search",
    Search_For: "Searching For",
    Share_Success: "Succeeded",
    Share_To: "Share to {0}",
    Emoticon: "Emoticon",
    Emoji: "Emoji",
    Add: "Add",
    Folder_Contact: "Folder shortcut",
    Shortcut_Contact: "Contact shortcut",
    Desktop_folder: "Folder",
    File_System: "Android file system",
    Devices: "Devices",
    Languages: "Languages",
    Contact_us: "Contact us",
    Move_To: "Move to",
    Workspace: "Workspace",
    Folder_Del_Alert_1: "Please empty the folder before deleting it.",
    Folder_Del_Alert_2: "This will delete all the content in the folder.",
    UserName: "User name",
    KeepLogin: "Stay signed in for 2 weeks",
    Already_have_account: "Sign in to continue",
    Authenticating: "Authenticating",
    PasswordIncorrect: "The email and password combination is incorrect. ",
    UserNameIncorrect: "The username is incorrect.",
    Connecting_To_Device: "Connecting to device...",
    Failed_To_Conn_Device: "Failed to connect to device.",
    Connect_Twiiter_reg: "Connect with Twitter to Register this username",
    Change_Diff_UserName: "Use a different username",
    SignUp: "Sign Up",
    Yes: "Yes",
    No: "No",
    UserNameValidateMsg: 'Only use letters, numbers and "_"',
    PasswordValidateMsg: "Password must contain at least 8 characters, including a number and a letter.",
    ConfirmPwdValidateMsg: "Passwords do not match.",
    EmailValidateMsg: "Please enter a valid email address.",
    EmailExist: "The email address is already registered.",
    Enter_Nickname: "Please enter nickname",
    Enter_NewPassword: "Please enter a new password.",
    ModifyProfileSuccess: "Modify settings succeeded",
    NavBar_SpeedInstall: "Speed install",
    NavBar_Setting: "Settings",
    SelectAll: "Select all",
    Import: "Upload",
    Cut: "Cut",
    Play: "Play",
    Rename: "Rename",
    Download: "Download",
    NewSms: "New Message",
    Message_NetWorkError: "Network Failure.",
    Label_NameColumn: "Name",
    Label_TimeColumn: "Time",
    ToolTip_FolderName: "Folder: ",
    ToolTip_PhotosCount: "Photos: ",
    ToolTip_Duration: "Duration:",
    ToolTip_CreateDate: "Date:",
    Tip_GridView: "Grid view",
    Button_Close: "Close",
    Button_Ok: "OK",
    Alert_Title: "Alert",
    msg_FileHasIllegalCharacter: 'The following characters are not supported:  / : * ? " < > ,| &',
    Message_LoadAppsConfigError: "Failed to load configuration file. Please click OK to sign in again.",
    Msg_AppsConfigNotLoaded: "Failed to load configuration file.",
    InputDynamicText_Search: "Search for apps",
    CategoryCountSuffix_Items: "item(s)",
    TipText_Edit: "Edit",
    Loading: "Loading...",
    No_Search_For: "No results",
    Shared_Via_Airdroid_Facebook: "shared from AirDroid",
    Shared_Via_Airdroid_Twitter: "shared from AirDroid",
    Share_Faile: "Failed",
    Logout: "Sign out",
    Account: "Account",
    About: "About",
    Password: "Password",
    Or_You_May_QR: "Scan QR code",
    Register: "Create an account",
    Enter_User_Password: "Please enter password.",
    isCheck: "Checking",
    Failed_To_Signin: "Failed to sign in.",
    Signin: "Sign In",
    AreYou: "Are you",
    ModifyProfileFail: "Modify settings failed",
    Call_Out: "Call",
    UnbindFailed: "Unbind Failed",
    NickName: "Nick name",
    Connect: "Connect",
    Disconnect: "Disconnect",
    OldPasswordIncorrect: "Current password incorrect.",
    NewPwdEqualOldPwd: "Password not changed, please try again.",
    RegFailded: "Failed to register.",
    UnbindSuccess: "Unbind Success",
    NewPassword: "New password",
    Email: "Email",
    OldPassword: "Current password",
    ConfirmPassword: "Confirm password",
    Save: "Save",
    Connected: "Connected as {0}",
    Bind: "Bind",
    NotBound: "No connected device.",
    FileLinkExisted: "There's already a shortcut for this folder.",
    Power_Saving_Tip: "Power saving mode activated and service stopped due to long time of inactivity.",
    UnboundS1: "Install AirDroid to the device you want to manage.",
    UnboundS2: "Open AirDroid and press the Account button.",
    QrNotSameWifiNoAccount: "To sign in via QR code, it's required to sign in to an account on the device, unless the device and computer are on the same WiFi network.",
    UseAccountLogin: "Sign in to an account.",
    TwitterAuthNameError: "Your twitter account name doesn't match {0}. Please try again.",
    EditContact_Success: "Edit contact icon success.",
    RequireLogin: "You need to create an account to use this feature.",
    RequestToAuth: "Please accept the connection on your device.",
    Send_Message: "Send message",
    Find_Phone: "Find Phone",
    SureToExitAndCloseTab: "Do you really want to quit and close this page?",
    UserCenterTabTip3: "Connect with SNS accounts to share photos with your friends. The SNS account you signed in with can not be disconnected.",
    ConnectWith: "Connect with {0}",
    Change: "Change",
    NotBoundDevice: "No connected device.",
    UserNameExist: "The user name is occupied.",
    UnboundS3: "Sign in to your account and refresh this page.",
    ProgramProcess: "Loading app resources...",
    Checking: "Verifying",
    SureToExit: "Do you really want to sign out?",
    UserCenterTabTip1: "The email address will be used to recover your password.",
    UserCenterTabTip2: "It's highly recommended to use a high-strength password to better protect your account security.",
    Thief_Tip1: "Never lose your phone again!",
    desktop_sound: "Notification sound",
    ChangeLangTip: "Restart AirDroid to take effect",
    Flow: "Data usage",
    FlowRemain: "Remaining: {0}",
    Contact_Tip: "AirDroid Internet is still under early beta test. To control our cost, there's a free monthly data usage quota of {0} for you. If you need more, please contact us. We may add options of increasing it later.",
    Forgot_Password: "Forgot password?",
    Login_With: "Sign in via",
    LostMode: "Lost mode",
    Thief: "Intruder",
    FindPhone_Num_Tip: "Enter a phone number that can reach you. It will be displayed on the lost device.",
    Button_Next: "Next",
    Thief_Tip3: "This feature is coming soon.",
    Drag_APK: "Drag & Drop APKs here",
    fill_require: "All fields are required.",
    rotate: "Rotate",
    placard: "Alerts",
    see_all_placard: "View all notifications",
    no_placard_tip: "No new alert",
    Searching_for_Device: "Searching for device",
    closing_camera: "Closing camera",
    forgot_password: "Forgot password?",
    login_with: "Sign in via",
    NoDeviceTip1: "No device found with this account",
    start_camera_error: "Failed to launch camera. Please exit camera on the device or {0} try again {1}.",
    Need_Premium: "This feature is only for Premium User. Do you want to upgrade to Premium User?",
    account_type: "User type",
    mem_since: "Membership",
    usage_month: "Data usage",
    upgrade_title: "Upgrade to Premium User",
    upgrade_des: "Get the ultimate AirDroid experience.",
    free: "Free User",
    premium: "Premium User",
    first_camera_tip: "Camera on the device will be temporarily disabled while you're using it in AirDroid.",
    DataFlowNotAbleToUpload_P: "Remote Connection Mode data quota not enough. You can use AirDroid in same network environment for free, or upgrade to AirDroid Premium to get more.",
    RemoteMode_FileTooLarge_F: "Size for single file cannot exceed {0} MB in Remote Connection Mode. To transfer larger files, please use AirDroid in same network environment, or upgrade to AirDroid Premium (up to {1} MB for a single file).",
    How_To_Sign_Up_Title: "How to register for an AirDroid account?",
    How_To_Sign_Up_S1: "Scan the QR code or <a href='{0}' target='_blank'>click here</a> to install AirDroid 2.",
    How_To_Sign_Up_S2: "Register for an account from AirDroid on your device and sign in.",
    Change_Email_Address: "Change email address",
    Confirm_Email: "Confirm email",
    Change_Email: "Change email",
    phone_location_close: "Location access not enabled on your device and Find Phone may not be able to locate your device.",
    ZoomIn: "Zoom in",
    ScanQRCodeToInstall: "Scan QR Code to Install",
    search_key_title: "Full text search",
    incoming_call: "Incoming call from {0}",
    notification_call_title: "Incoming call",
    message_to: "To:",
    add_contact: "Add to contacts",
    check_contact: "View contact",
    new_message: "New message",
    new_message_to: "New message",
    close_desktop_notification: "Disable desktop notifications",
    QCC_Confirm_payment: "Confirm payment",
    QCC_Tip_2: "Item: Remote Connection Extra: 1GB.",
    QCC_Tip_3: "Please don’t close this page before the payment is completed.",
    QCC_BTN_2: "Start over",
    QCC_Fail_1: "Bank account was charged but failed to activate the item?",
    QCC_Fail_2: "It may be a result of network delay. Please don’t worry. We’ll restore it as soon as possible.",
    QCC_Fail_3: "Bank account was not charged?",
    upgrade_title1: "Remote Connection Mode quota used up?",
    QCC_Tip_7: "The pack will be added to the current month of your Premium membership.",
    total: "Total",
    Price: "Price: ",
    QCC_Fail_4: "You can try to make the payment again. If still no luck, please contact PayPal or your bank",
    Increase_Quota: "Increase Quota",
    Button_Previous: "Previous",
    uninstall_app_tip: "Confirm uninstallation on your phone",
    check_find_phone: "Checking if Find Phone is activated...",
    connect_1: "Searching for device...",
    connect_3: "Checking network...",
    connect_4: "Using LAN Connection Mode...",
    connect_5: "Using Remote Connection Mode...",
    connect_6: "Found your device",
    connect_7: "Woke up successfully",
    connect_8: "Failed to wake up",
    connect_12: "Connected to device",
    connect_13: "Failed to connect to device",
    operate_fail: "Sorry, your device is not supported yet.",
    connect_14: "Network checking completed",
    LiteConnectMode_tip: "You may need to wait for a few seconds for the alert to appear on your device.",
    ConnFAQ: "Still cannot connect? Try more detailed guide",
    delete_account: "Delete account ",
    delete_account_msg: "You can contact us directly if you need any help: {0} support@airdroid.com{1}.",
    tell_why: "Reason for leaving",
    opt_select_a_option: "Choose an option",
    opt_change_email: "I want to change email",
    opt_unbind_sns: "I want to disconnect SNS account",
    delete_failure_try_later: "Failed to delete your account. Please retry later.",
    tip_reason_null: "Please choose your reason for leaving.",
    tip_reason_change_email: "You can {0} change your account email {1} in AirDroid.",
    item_1: "Item: AirDroid Premium 1 Month",
    item_3: "Item: AirDroid Premium 2 Years",
    usepaypal: "*Pay with PayPal",
    Pay_w: "Item",
    Pay_o: "Order",
    Pay_p: "Payment type",
    Pay_t1: "Only displays purchase history from the last 24 months",
    Pay_t3: "All prices include tax",
    select_group: "Select group",
    create_success: "Create success",
    edit_success: "Saved successfully",
    edit_failed: "Failed to save",
    sure_delete_group: "Are you sure you want to delete group {0}?",
    group_name_null: "Please input group name",
    new_group_label: "New group",
    click_detail_contact: "Click contact to show details",
    label_blog: "Blog",
    label_ftp: "FTP",
    label_website: "Website",
    add_group: "Add group",
    contact_need_tip: "Phone and Name are required.",
    confirm_save_contact: "Save modification?",
    Pay_total: "Total",
    group_repeat: "The group name is already in use.",
    premium_renewals: "Renew",
    premium_expire_tip: "Your Premium membership will expire on: {0}.",
    premium_extend: "Renew",
    payment_account_success: "Your payment for AirDroid Premium has been successfully received.",
    no_thieves_found: "No intruders detected:",
    cancel_autopay: "Cancel subscription",
    success_cancel_autopay: "You've successfully canceled your Premium subscription.",
    find_my_phone_instruction: "Help",
    no_thief_tip1: "You need to turn on screen lock in your device's settings or via AirDroid Lost mode in Find Phone.",
    no_thief_tip2: "AirDroid will use the front camera to take a photo of the intruder who attempted but failed to unlock your device. Location data will also be included when available.",
    get_device_location_failure: "Failed to retrieve location data",
    add_to_desktop: "Add to desktop",
    delete_from_desktop: "Delete from desktop",
    load_again: "Click {0}here{1} to reload",
    normal: "General",
    desktop_notification: "Desktop notification",
    email_subscription: "Emails",
    "default": "Set default",
    email_tip1: "AirDroid news",
    email_tip2: "Promotion messages",
    add_desktop_success: "Added successfully",
    remove_from_desktop_success: "Deleted successfully",
    connect_stop_tip: "Connection interrupted. Please check the network and retry.",
    connect_device_error: "Failed to connect Android device. Please check the network.",
    reconnect_expired: "Please sign in again for account security.",
    email_success_tip1: "An email was sent to your email address: {0}. Please click the verification link to verify your address.",
    click_new_contact: 'Click "New contact" to create a new contact',
    send_email_timer: "Resend in {0}s",
    need_connect_device: "Error. Your Android device is disconnected. Please connect again to continue.",
    item_4: "Item: AirDroid Premium 1 Month - Starter plan",
    select_pay_mode: "Select your AirDroid Premium plan",
    select_pay_mode_tip: "Upgrade to AirDroid Premium to enjoy all the Premium features.",
    premium_cancel_autopay: 'Auto renew (can be canceled later in "Account")',
    premium_feature_list_title: "Premium Exclusives",
    label_month: "Month",
    label_year: "Year",
    label_years: "{0} Years",
    premium_year_des: "Buy 2 years and get 1 year for free",
    premium_icon_hot: "Popular",
    premium_icon_value: "Best value",
    connect_device_name_tip: "Connecting to {0}, please wait...",
    select_default_device_tip: "Connect this device by default next time",
    select_your_device: "Choose a device",
    select_a_device: "Choose a device",
    select_a_device_tip: "Sorry, there're {0} devices under your account. Multiple device support is a Premium exclusive feature. You can choose to upgrade to Premium account or select 1 device and delete others.",
    unbind_device_success_tip: "Device deleted.",
    unbind_device_fail_tip: "Failed to delete device. Please retry.",
    add_devices: "Add device",
    add_more_devices: "Add more devices",
    unbind_device_tip: "You are trying to delete {0}. To ensure the security of your device, please enter your AirDroid password.",
    bind_more_tip: "To add a new device, please go to that device and sign in to the current AirDroid account.",
    unlock: "Unlock",
    unlock_tip: "Please note that this feature will remove the screen lock password of the device. Continue?",
    wipe_premium_tip: "This will reset your device to factory default. All personal data will be wiped.",
    present_t1_content: "Samsung Chromebook 2 Only. Sponsored by Samsung and AirDroid.",
    present_t2_check_eligibility: "Checking eligibility, please wait...",
    present_t3_success_content: "Congratulations, you're now an AirDroid Premium user.",
    present_t4_fail_content: "Redemption failed. Possible causes:",
    present_t4_fail_tip1: "1. The offer has already been redeemed on your device.",
    present_t5_about: "What is AirDroid?",
    present_t5_intro_title1: "One less cable",
    present_t5_intro_content1: "Move things on and off your Android device without a USB cable.",
    present_t5_intro_title2: "One less screen",
    present_t5_intro_title3: "One less worry",
    present_t5_intro_content3: "Lost your phone? No worry, use AirDroid to locate or lock it remotely.",
    present_t6_retry: "Retry",
    present_server_error: 'Connection failed. Please check your network and click "Retry" later.',
    present_login_signUp: "Sign up",
    present_login_signWith: "or sign in with",
    present_loginBefore_btn: "Sign in to Redeem",
    present_loginAfter_btn: "Redeem",
    email_verify: "Email not verified. Verify now",
    email_verify_tip: "Email not verified",
    set_external_sdcard_tip: "If the external SD card is not detected, please set it manually.",
    set_external_sdcard: "Add external SD card",
    delete_external_sdcard_tip: "Delete the external SD card?",
    switch_device_label: "Switch device",
    delete_file: "Delete file",
    android_version_no_support_tip: "Android 2.1 and lower is not supported by AirDroid 2.0.7 and later. You can continue with the existing version.",
    default_replace_user_des: "If default user configuration file is loaded, some settings like desktop icons and shortcuts will not be saved. Other features will not be impacted.",
    use_default_appconfig: "Load default",
    add_device_title: "Add a device",
    save_to_pc: "Save to computer",
    click_to_choose_external_sdcard: "Choose external SD card path",
    camera_save_to_phone_success: "Photo saved to device",
    server_network_error_tip: "Failed to access server, please {0}retry{1}.",
    keep_device_tip: "Choose 2 devices to keep:",
    premium_expire_title: "Renew Your Premium Subscription",
    lights_on: "Flashlight on",
    lights_off: "Flashlight off",
    device_nickname: "Device name",
    pay_success: "Succeeded",
    pay_fail: "Failed",
    pay_type_code: "Activation Code - {0}",
    save_percent: "Save {0}",
    lable_or: "or",
    scan_qr_tip: "Scan the QR code",
    free_user_add_device_tip: "Free account can only connect 2 devices. Upgrade to Premium account to connect up to 6.",
    reserve_attach_confirm: "The file is available for download within 7 days and then will be permanently deleted.",
    fail_to_upload: "Failed to upload the file",
    attach_amount_limit: "Only one attachment per message please.",
    cancel_all: "Cancel all",
    cut_file_success: "Files cut",
    drag_drop_or_click_to_upload: "Drag & Drop files or folders here to upload",
    label_forgot: "Forgot",
    device_set_default: "Connected by default on signing in:",
    mark_all_read: "Mark all as read",
    delete_account_msg2: "We’re sorry to see you go.",
    no_default_device: "choose a device",
    video_fluency_tip: "Loading time and video smoothness will depend on network quality.",
    release_to_beta_tip: "It seems that you're using a beta version of AirDroid. You'll be redirected to the corresponding web app for it.",
    Msg_Srv_Unavailable_3: "Try Lite mode if your Android device and computer are on the same WiFi network.",
    cancel_desktop_notification: "You can re-enable AirDroid desktop notifications in Chrome if you've disabled them before.",
    Lite2Web_title1: "Get the most out of AirDroid",
    Lite2Web_desc1: "You're using Lite mode. Visit the full version at {0}.",
    SNS: "SNS",
    chromebook_question: "Any question, please send your device model# to {0}support@airdroid.com{1} for assistance.",
    contact_no_name: " (No name) ",
    Enter_User_Name: "Please enter user name.",
    Enter_Email: "Please enter email",
    Enter_OldPassword: "Please enter the current password.",
    ChangePwdFail: "Failed to change password.",
    UsernameUsedOnTwitter: "The user name exists on Twitter",
    ContactLinkExisted: "There's already a shortcut for this contact.",
    Account_Logout_Tip: "The account is signed out on the mobile app and service has stopped!",
    RequestRefused: "Connection rejected by device.{0} You can refresh this page to try again.",
    MonthDataFlowOverage: "Your monthly data quota for Remote Connection Mode is used up and you'll no longer be able to use some features under Remote Connection Mode.",
    FlowTip: "Data usage for this month",
    FlowRecover: "Quota reset in {0} day(s)",
    How_To_Sign_Up: "How to sign up?",
    Input_Optional: "Optional",
    Tip_Number: "Phone number",
    Thief_Tip2: "AirDroid can take a photo of the face of the intruder who tried and failed to unlock your device.",
    adjusted_registration_tip: "We've adjusted the registration process for better experience. Username is removed from AirDroid 2 and you can only use Email and password to sign in.",
    continue_use_oldversion: "Update next time",
    two_passwords_dont_match: "Email addresses don't match.",
    not_change: "New email is same as the current one.",
    change: "Switch",
    no_support_camera: "The feature is not supported for your current Android version (2.2 or lower).",
    placard_read: "Mark as read",
    placard_detail: "Details",
    NoDeviceTip2: "Please connect a device to your account to continue",
    Remote_Need_Premium: "This feature (under Remote Connection Mode) is only for Premium User. There is no restriction under same network environment. Do you want to upgrade to Premium User?",
    Free_User_Overage_Tip: "The free Remote Connection Mode data quota is exhausted. You can use AirDroid in same network environment for free, or upgrade to AirDroid Premium to get more. ",
    Upgrade_to_Premium_User: "Upgrade to Premium User",
    Premium_User_Overage_Tip: "The Remote Connection Mode data quota in your AirDroid Premium plan is exhausted. ",
    How_To_Sign_Up_S3: "Sign in on the web side with the same credential.",
    New_Email: "New email",
    google_server_unable: "Some services are not available or for other unknown reasons, Find Phone may not be able to locate your device.",
    ZoomOut: "Zoom out",
    login_with2: "Sign in via {0}",
    Update_Beta_Title: "AirDroid Updated",
    or: "or",
    Update_Beta_Title2: "AirDroid was just updated. Please update your AirDroid to the latest version for better experience. {0} Update now {1}",
    search_name_title: "Contact name search",
    notification_message_title: "New message",
    open_desktop_notification: "Enable desktop notifications",
    account_setting: "Settings",
    QCC_Tip_1: "Please finish the payment in the new page.",
    QCC_Tip_4: 'After you make the payment successfully, click "I\'ve made the payment" or close this window to finish the purchase process.',
    QCC_FailTitle: "The payment was not successful. Please check if your bank account has been charged.",
    QCC_Fail_5: "You can also email us for further assistance: pay@airdroid.com",
    "1gbExtra_add_success": "The 1GB Remote Connection Extra has been added to your account.",
    QCC_BTN_1: "I've made the payment",
    upgrade_des1: "Add 1 GB Remote Connection Extra to your Premium account for only $1.99.",
    QCC_Tip_5: "Remote Connection Extra: 1 GB",
    QCC_Tip_6: "Get another 1 GB remote connection quota for only $1.99.",
    QCC_Tip_8: "The pack expires on {0} ({1} day(s) remaining).",
    phone_auth_failed: "Failed to connect device. [Error: 10001] Please retry.",
    Update_1x_Title2: "AirDroid was just updated. Please update your AirDroid to the latest version for better experience. {0} Update now {1}",
    install_app_tip: "Confirm installation on your phone.",
    connect_2: "Waking up device...",
    connect_9: "Connection Mode: LAN Connection Mode",
    connect_10: "Connection Mode: Remote Connection Mode",
    connect_11: "Connection established",
    ReConnect: "Reconnect",
    tell_detail: "Help us improve AirDroid by sharing some detailed feedback (Optional)",
    opt_dont_want_to_use: "I don't want to use AirDroid any more",
    opt_have_other_account: "I have another AirDroid account",
    other: "Other",
    delete_success: "Account successfully deleted.",
    item_2: "Item: AirDroid Premium 1 Year",
    Pay_t: "Payments",
    Pay_d: "Date",
    Pay_t2: "Refund records are not displayed",
    operate_success: "Success ",
    edit_group_label: "Edit group",
    sure_delete_contacts: "Delete these contacts?",
    label_homepage: "Homepage",
    add_field: "Add field",
    label_profile: "Account",
    label_address: "Address",
    group_name_label: "Group name",
    no_purchase: "No payments",
    upgrade_premium: "Upgrade to Premium",
    go_premium: "Go Premium",
    cancel_autopay_tip: "You'll be downgraded to free account when your current subscription expires. You can always subscribe again. ",
    sure_to_cancel: "Are you sure you want to cancel your subscription? ",
    Thief_Tip4: "The feature is exclusive to Premium users. Upgrade now?",
    geocode_device_location_failure: "Failed to parse the location data",
    Message_LoadUserConfigError: "Failed to load user configuration file. Please click OK to sign in again.",
    lab_tip1: "AirDroid Lab is a playground for new features. We'll regularly release new features when they're ready for public test.",
    lab_tip2: "All the lab features are experimental, and they may break or disappear at any time.",
    label_reconnect: "Reconnect",
    connect_device_tip: "Connecting to Android device...",
    loadErrorTip: "Failed to load. Please check the network and retry.",
    labT1: "Features",
    labT2: "Requirements",
    email_verify_fail: "Failed to send email. Please retry later.",
    sending_email: "Sending email...",
    premium_month_des: "Starter plan, 1 GB Remote Connection Mode data quota.",
    sms_cannot_delete_tip: "Sorry, AirDroid does not support deleting SMS  on Android 4.4.",
    cancel_default_device: "Remove default",
    connect_other_device: "Connect another device",
    label_choose: "Choose",
    switch_device: "Switch",
    default_connect_device: "Default device",
    unlock_success_tip: "Screen lock password is removed.",
    switch_update_tip: 'The AirDroid app on your device is not the latest one. Please update the app. Or, if you want to keep it, please click "Update next time".',
    unlock_failed_tip: "Failed to remove screen lock password.",
    present_t1_about: "What's AirDroid",
    present_t1_theme: "AirDroid Premium 1 Year Gift",
    present_t3_success_expire: "Your Premium term: {0}",
    present_t4_fail_tip2: "2. Currently only selected Samsung Chromebooks are eligible for this offer.",
    present_t5_about_description: "AirDroid is a free and fast Android app that helps you manage your Android phone/tablet from a web browser, all over the air.",
    present_t5_about_learnMore: "Learn more",
    present_t5_intro_content2: "Send & receive SMS on computer, without looking at phone screen.",
    present_login_skip: "Skip",
    present_start_airdroid: "Start AirDroid",
    default_replace_user_tip: "Failed to load your user configuration file. You can choose to load the default one or try again (Reload).",
    label_reload: "Reload",
    save_to_phone: "Save to phone/tablet",
    screenshot_save_to_phone_success: "Screenshot saved to device",
    premium_down_des: "Your Premium membership has expired. You'll need to renew your subscription to keep all the devices with your account. Or, you can only keep up to 2 devices.",
    apk_decode_error: "There was problem parsing the package.",
    pay_status: "Status",
    lights_on_fail: "Failed to turn on flashlight.",
    UnboundTitle: "No device found with your account. Please add a device to continue:",
    UnboundS4: "{0}Install AirDroid{1} to the device you want to manage.",
    input_site_name_and_url_please: " Please enter website name and URL",
    share_services: "Sharing services",
    attach_size_limit: "Maximum size: 10 MB",
    copy_file_success: "Files copied",
    attach_past_due: "File expired.",
    label_verify: "Verified",
    device_number_tip: "Number of devices connected: {0} ",
    camera_fluency_tip: "The actual frame rate can be affected by several factors including network quality, camera resolution and other specs of the Android device.",
    beta_to_release_tip: "It seems that you're using a production version of AirDroid. You'll be redirected to the corresponding web app for it. You can {0}join our test community{1} to become a beta tester.",
    notification_set_setp1: "Click the 'View site information' button.",
    notification_set_setp2: 'Choose the "Always allow on this site" option in "Notifications"',
    Lite2Web_title3: "Find phone and protect data",
    Lite2Web_desc3: "Locate your phone, and wipe all data if you cannot get it back.",
    Lite2Web_title4: "Connect all your Android devices",
    Lite2Web_desc4: "Connect all your Android devices to the same account.",
    Lite2Web_desc2: " Access your Android device remotely through any network.",
    Lite2Web_title2: "Local or remote network",
    How_to_set_notication: "How to set desktop notifications in other browsers",
    upload_Permission_Denied: "Failed to upload. No write permission to SD card.",
    upload_network_error: "Failed to upload. Network error.",
    pop_window_disabled_des: "The pop-up was blocked. Please enable the pop-up from www.airdroid.com and click OK to continue.",
    change_path: "Set file saving path on Android",
    delete_thief_confrim: "Are you sure you want to delete this record?",
    url_link_exist: "The URL name already exists. ",
    flash_player_update: "Your Flash Player version is not supported. Please upgrade it to the latest version.",
    browser_nosupport_title: "Your web browser is not supported. Please upgrade to the latest version or try one of the following browsers.",
    PlaySound: "Ring",
    mem_tip: "{0} day(s) remaining",
    attach_load_fail: "Failed to load file.",
    delete_thief_fail: "Failed to delete",
    click_to_choose_path: "Select",
    MainAccount: "Registration account ",
    external_sd_might_be_limited: "External SD card access may be restricted",
    external_sd_might_be_limited_detail: "Due to system restrictions of Android 4.4+, some operations like uploading, deleting and creating new files on the external SD card may not be supported.",
    open_desktop_sound: "Enable notification sound",
    NavBar_Dashboard: "Widgets",
    find_phone_connect_fail: "Failed to connect. Your device is probably not connected to networks.",
    present_need_login: "Tip: Make sure you have signed in to this Chromebook using your Google account."
}, Airdroid.Lang.SSLTip = {
    Btn_Donotremind: "Don't display this next time.",
    Tip_SSLCommon: "Hypertext Transfer Protocol Secure (HTTPS) provides encrypted communication and secure identification. Your browser may display a warning and you can safely ignore it. This message appears because the certificate used by AirDroid is self-signed. Example:",
    Tip_Chrome: 'Google Chrome will display a warning titled "The site\'s security certificate is not trusted!" the first time your try to sign in via secured connection option. Click “Proceed anyway” to continue.',
    Tip_FFStep1: 'Firefox will display a warning titled “"This Connection is Untrusted" the first time your try to sign in via secured connection option. Click "I Understand the Risks", then "Add Exception".',
    Tip_FFStep2: 'Click "Confirm Security Exception" to continue. ',
    Tip_Safari: 'Safari will display a warning titled "Safari can\'t verify the identity of the website xxxx" the first time your try to sign in via secured connection option. Click "Continue" to login.',
    Btn_Gotit: "Got it."
}, Airdroid.Lang.SMS = {
    ToolTip_Call: "Call out",
    Chat_MoreMessage: "More messages",
    ContactSelectorDefault: "Select a custom group...",
    MIUI_SMS_Line1: 'Click Send again, then tap "Allow" on your Android device to grant AirDroid the permissions needed.',
    MIUI_SMS_Line2: "If your Android device is not notifying you, please go to your permission management app (like Superuser) to manually grant AirDroid SMS permissions.",
    Message_MultiChatTaskItem: "Chat ({0})",
    TimestampTip: 'Wrong timestamp on message? Click "Settings" to correct it.',
    Message_ContactInfoSaveSucceed: "Contact info saved.",
    Message_ContactInfoSaveFailure: "Failed to modify contact.",
    Message_CreateContactInfoSucceed: "Contact created.",
    Message_CreateContactInfoFailed: "Failed to create contact.",
    Message_ReadContactInfoFailed: "Error while loading contact info.",
    Message_SureToDeleteCallLog: "Are you sure you want to delete this call log?",
    Message_Loading: "Loading...",
    Message_SmsSendSucceed: "Message sent.",
    Message_SureToDeleteSelectedThread: "Are you sure to delete the selected threads?",
    Message_LoadGroupsFailure: "Failed to load groups.",
    Message_LoadCallLogsFailure: "Failed to load call logs.",
    Message_DeleteCallLogFailure: "Failed to delete this call log.",
    CallLog_Lable_TypeColumn: "Call",
    CallLog_Lable_TimeOfCalls: "Time",
    CallLog_Lable_DurationColumn: "Duration",
    Chat_TabName_Chat: "Chat",
    Chat_Button_Send: "Send",
    Chat_ToolTip_EnterToSend: "[Enter] to Send",
    Sms_ToolTip_Delete: "Delete",
    Contact_Label_Name: "Name",
    Contact_Label_Group: "Group",
    Contact_Label_Search: "Search",
    Contact_Label_WorkPhone: "Work",
    Contact_Label_WorkFax: "Work Fax",
    Contact_Label_OtherPhone: "Other",
    Contact_Label_Note: "Note",
    Contact_Button_Save: "Save",
    Message_PhoneSelected: "selected",
    ToolTip_ClickToChat: "Start SMS chat",
    Message_DeleteCurrentChatFailure: "Failed to delete selected thread(s).",
    Message_CreateContactInfo: "There is no phone number with this contact. Edit?",
    Message_DeleteMessageFailure: "Failed to delete this message.",
    Message_NotAllLoaded: "Failed to load all contacts in this group.",
    Message_SureToDeleteCallLogs: "Are you sure you want to delete the selected call logs?",
    Message_NotAllCallLogDeleted: "Error. Only some of the selected call logs were deleted.",
    ToolTip_DeleteCallLog: "Delete this call log",
    ToolTip_CreateContactInfo: "Create new contact with this number",
    Message_LoadingThreadListFailure: "Failed to load SMS threads.",
    Message_NotAllThreadDeleted: "Error. Only part of the selected threads deleted.",
    Message_LoadingGroupContactsFailure: "Failed to load group contacts",
    Contact_Lable_NumberColumn: "Number",
    Message_SendFailBecauseOfARConn: "Error while communicating with device.",
    Confirm_ReSendThisSMS: "Are you sure to resend this message?",
    Message_SendFailBecauseOfRErrId: "Failed to send message. Please check on your device if it's successfully sent.",
    Message_CreateChatWindowError: "Error while loading.",
    Message_SendFailBecauseOfDataErr: "Error. Failed to send message.",
    ToolTip_PleaseWait: "Please wait...",
    Count_Contacts: "{0} Contacts",
    Cut_Fail: "Cut failed",
    CallogTab_All: "All",
    CallogTab_Incoming: "Incoming",
    CallogTab_Outgoing: "Outgoing",
    CallogTab_Missed: "Missed",
    Message_CanNotDeleteContact: "Can't  edit contact while loading.",
    Message_ReadSmsError: "Failed to load new message.",
    CallLog_Lable_NameColumn: "Name",
    CallLog_Lable_NumberColumn: "Number",
    Chat_TabName_ContactInfo: "Contact info",
    Chat_TabName_CallLog: "Call Logs",
    Chat_ToolTip_EnterCtrlToSend: "[Ctrl+Enter] to Send",
    Contact_Label_Phone: "Number",
    Contact_Label_MobilePhone: "Mobile",
    Contact_Label_HomePhone: "Home",
    Contact_Label_HomeFax: "Home Fax",
    Contact_Button_Create: "Create",
    Sms_Button_SelectContact: "Contacts",
    Lable_SmsTo: "To",
    Message_SureToDeleteMessage: "Are you sure you want to delete this message?",
    Message_ReveivedMessage: "Received {1} message(s) from {0}",
    Message_LoadingSMSFailure: "Error while loading SMS threads.",
    Contact_Lable_NameColumn: "Name",
    Message_InputContactSenseFailure: "No matches.",
    Message_NumberAndContentNeeded: "Number and Content are required.",
    Message_ContactFormatErrorOrPositionErrorFromPasted: "Invalid format or location error.",
    Button_NewContact: "New contact",
    Contact_all_numbers: "All phone numbers",
    ToolTip_NamesNumbersSeparateComma: "Input names or numbers and separate them with comma.",
    Message_ConfirmToDeleteContact: "Are you sure you want to delete contact {0}?",
    Message_SureToDeleteThisThread: "Are you sure to delete this thread?",
    Message_StarFieldIsNeeded: "Fields marked with an asterisk (*) are required.",
    ToolTip_RequirePermission: "Permissions are required on your device to send SMS via AirDroid.",
    Contact_all: "All contacts"
}, Airdroid.Lang.Upload = {
    Button_SelectFolder: "Select folder",
    Message_SuportFileTypes: "Supporting {0}",
    Msg_not_avail: "Failed to upload. Not enough free space on SD card. ",
    Message_SureToStopUploadFiles: "Will stop uploading. Are you sure to close the window?",
    Label_FileTypesDesc: "Select files",
    Lable_InstallApps: "Install apps",
    Label_PhotoTypesDesc: "Select photos",
    Label_MusicTypesDesc: "Select music",
    Label_RingtoneTypesDesc: "Select ringtones",
    WindowTitle_ImportRingtones: "Upload ringtones",
    WindowTitle_ImportMusic: "Upload music",
    WindowTitle_ImportPhotos: "Upload photos",
    WindowTitle_ImportFiles: "Upload files",
    Label_UPloadSucceed: "Success",
    Label_UploadFailure: "Failed",
    notsupportdragfolders: "Drag & Drop for folders is not supported under current browser.",
    OnlySupportChrome: "Folders upload is only supported by Chrome.",
    FileDropTip: "Drag & Drop files or folders here to upload",
    ApkDropTip: "Drag & Drop apps here to install",
    Tip_UploadTo: "Target folder: {0}",
    Msg_File_TooLarge: "File size exceeds the limit of your web browser.",
    DataFlowNotAbleToUpload: "Your remaining monthly data quota for Remote Connection Mode is not enough for transferring this file.",
    Label_ProgressColumn: "Progress",
    Button_SelectFiles: "Select files",
    Button_ClearSucceed: "Clear uploaded",
    ToolTip_ClearSucceed: "Clear uploaded files",
    Label_ApkSucceedTip: "Success. Proceed on device.",
    Label_UPloadCanced: "Canceled",
    Label_UploadWaiting: "Waiting",
    NameExistSureRename: "Folder {0} already exist. Rename as {1}?",
    RemoteMode_FileTooLarge: "Size for single file cannot exceed {0} MB in Remote Connection Mode. To transfer larger files, please use AirDroid in same network environment."
}, Airdroid.Lang.Applications = {
    Message_Uninstalling: "Uninstalling...",
    Message_UninstallError: "App not installed or is already uninstalled.",
    Message_InstallingApp: "Installing [{0}]...",
    Message_UninstallApp: "Uninstalling [{0}]...",
    Message_SureToUninstallSelectedApp: "Uninstall the selected {0} apps?",
    Message_Uploading: "Uploading...",
    TabName_UserApp: "User",
    Button_InstallApp: "Install app",
    Message_TapOnDevice: "Tap on device",
    Button_InstallUnknownSourceAppGuide: "User guide",
    ToolTip_InstallUnknownSourceApp: 'To allow installation of non-Market apps, please enable "Unknown sources" on your Android.',
    Message_LoadAppListError: "Failed to load apps list.",
    Message_ConfirmToUninstallApp: "Are you sure to uninstall {0}?",
    Message_UploadingError: "Error while uploading {0}.",
    Message_InstallingAppError: "An error occurred during installation.{0}Operation aborted.",
    Message_ActionDone: "OK",
    Message_NOfAppsProhibited: "Copying of below {0} app(s) is prohibited.",
    Message_AppProhibitedTip: "Copy Protection is a publishing option by developers to prevent copying of their apps from the device.",
    Label_InstallTip: "Proceed on your Android to complete the installation.",
    Message_ReinstallStartSuc: "Re-installation triggered. ",
    Suffix_InstallInQueue: "queuing",
    ZipName_AppDefaultExportName: "Apps_downloaded_by_AirDroid",
    Message_SelectApp: ".apk",
    Message_UninstallSucceed: "Uninstall success.",
    TabName_SystemApp: "System",
    TabName_Recommends: "Recommends",
    Button_UninstallApp: "Uninstall",
    Label_InstalledDateColumn: "Date installed"
}, Airdroid.Lang.BrowserTip = {
    BrowserTip1: "{0}We keep improving AirDroid's performance on various browsers.{1}{2}For best performance we highly recommend that you choose one of the{3}{4}recommended browsers(listed below).{5}",
    BrowserTip2: "Support for other browsers is experimental.",
    BrowserGo: "Continue with the current browser. >>"
}, Airdroid.Lang.Filemanage = {
    Message_FileItemMore: "More than 250 files are selected. It may take a while to load. Continue?",
    Msg_NOSdCard: "SD Card not found",
    Msg_LoadFileTreeError: "Failed to load folder tree.",
    ZipName_FileDefaultExportName: "Files_downloaded_by_AirDroid",
    Message_FileExist: "A folder named {0} already exists. Please use another name.",
    Message_SureToDeleteFile: "Are you sure you want to delete this file?",
    Message_SureToDeleteSelectedFiles: "Are you sure you want to delete these {0} files?",
    Message_ListFolderFailure: "Failed to load folder {0}.",
    Message_RenameFailure: "Failed to rename {0}.",
    Message_SelectNoFiles: "No files selected.",
    Label_NewFolderName: "Folder name",
    Message_FileHasIllegalCharacter: "A file name can't contain any of the following characters:  / : * ? \" < > ,| &",
    Message_CreateFolderFailure: "Failed to create folder {0}.",
    FileName_tooLong: "File name must be within {0} characters.",
    Message_FileNameExist: "A file with the same name already exists.",
    MenuItem_Move: "Move",
    Message_FolderSummary: "{0} items",
    ExternalSD_Directory: "External SD",
    SDCard_Directory: "SD Card",
    SystemDirectoryWarn1: "Warnings",
    CreateShortcut: "Create desktop shortcut",
    Message_CopyOrCutSucceed: "{0} files success.",
    Label_NewName: "New name",
    Message_SameFileName: "File name remains the same.",
    Message_FileNameIsNull: "You need to type a file name.",
    ToolTip_SelectedFiles: "{0} items selected",
    Message_CopySelfError: "The destination folder is a subfolder of the source folder.",
    System_Directory: "System",
    SystemDirectoryWarn2: "Modifying or deleting system files may cause system error, please be cautious.",
    SystemDirectoryWarn3: "Operations on some system files may fail due to unpredictable file permissions.",
    Action_Permission_Denied: "Operation failed. No write permission to SD card."
}, Airdroid.Lang.Hotkeys = {
    Lbl_ctrl_v: "Paste",
    Lbl_ctrl_c: "Copy",
    Lbl_ctrl_a: "Select all",
    Lbl_f2: "Rename",
    Btn_Hotkeys: "Hotkeys:",
    Lbl_HotkeysList: "Hotkeys:",
    Lbl_ctrl_x: "Cut",
    Lbl_delete: "Delete"
}, Airdroid.Lang.Summary = {
    Coming_soon: "Coming soon",
    Label_Music: "Music",
    Label_Videos: "Videos",
    Label_Photos: "Photos",
    Label_Contacts: "Contacts",
    Label_Messages: "Messages",
    Label_InternalStorage: "Internal Storage (Available: {0})",
    Label_SDStorage: "SD Card (Available: {0})",
    Message_ReadAndroidSummaryError: "Error.",
    Button_SummaryDetail: "Detail",
    Label_Other: "Other",
    Label_Apps: "Apps",
    Label_eBooks: "Books",
    Title_InternalStorage: "Internal storage",
    Title_SDStorage: "SD Card",
    Title_exSDStorage: "External SD Card",
    Label_exSDStorage: "External SD Card (Available: {0})"
}, Airdroid.Lang.Modules = {
    SummaryDetail: "Summary",
    Messages: "Messages",
    Apps: "Apps",
    Files: "Files",
    Music: "Music",
    Contacts: "Contacts",
    CallLog: "Call Logs",
    NewContact: "New contact",
    upload: "Upload files",
    WebBrowser: "Web Browser",
    EditContact: "Edit contact",
    Chat: "Chat",
    NewMessage: "New message",
    SelectContacts: "Select contacts",
    Video: "Videos",
    Recommends: "Recommends",
    MessageSettings: "Message settings",
    Installapps: "Install apps",
    quickupload: "Upload files",
    Screenshot: "Screenshot",
    Camera: "Camera",
    Photos: "Photos",
    Ringtones: "Ringtones",
    VideoPlayer: "Video Player",
    AudioPlayer: "Audio Player",
    FrequentContacts: "Frequent",
    Quixey: "Quixey",
    Settings: "Settings",
    FindPhone: "Find Phone",
    Language: "Language",
    UserCenter: "Account",
    Increase_Quota: "Increase Quota",
    Premium: "Premium",
    ContactCut: "Crop picture",
    Lab: "Lab",
    Gift: "Gift",
    FeedBack: "Feedback",
    Help: "Help",
    Add: "Add",
    DesktopContact: "Contact shortcut",
    DesktopFileList: "Folder shortcut"
}, Airdroid.Lang.Video = {
    VideoCategory_Camera: "Camera",
    VideoCategory_Others: "Others",
    Btn_PlayAnyway: "Play anyway",
    Tip_FormatNotSupported: "Video format not supported. You can try download and play it using your desktop video player.",
    Message_ReadVideoListError: "Error while loading videos list.",
    Message_DeleteFail: "Error while deleting videos.",
    Message_DeleteSuc: "Delete success.",
    Confirm_DeleteSingleVideo: "Are you sure you want to delete this video?",
    Confirm_DeleteMultiVideos: "Are you sure you want to delete the selected videos?",
    Confirm_DeleteAllVideos: "Are you sure you want to delete all videos?",
    Message_StreamNotFound: "Stream not found.",
    Message_NoSupportThisType: "Video format not supported. ",
    Tip_VideoTooLarge: "This video is larger than 100MB. We suggest that you download it before play.",
    Tip_CannnotPlay: "Failed to play video. You can try download and play it using your desktop video player.",
    Message_VideoPlayerError: "Player error.",
    Message_ReadVideoSummaryError: "Error while loading videos summary.",
    CategoryCountSuffix_Items: "item(s)",
    Tip_QuickTime_Installation_1: "Please follow the browser's instructions or <a target='_blank' href='{0}'>download QuickTime here</a> to view the video.",
    Tip_QuickTime_Installation_2: "Restart your browser after the installation."
}, Airdroid.Lang.Screenshot = {
    Tip_GrantRootPerm: "If your Android device is not notifying you, please go to your root permission management app (like {0}) to manually grant AirDroid root permissions.",
    RootTip_Root_Q_1: "What are root permissions, rooting, root access?",
    RootTip_Root_Q_2: "How to grant AirDroid the root permissions required?",
    RootTip_Root_A_2_2: "After your Android device is rooted, open AirDroid and try the Screenshot feature again. It’s awesome, especially the experimental ability to view everything on your android’s screen in real-time.",
    RootTip_Root_Q_3: "Why root permissions are required by AirDroid to capture screenshots?",
    Tip_AllowRootPerm: "If your device is already rooted, please press Allow on your Android device to grant AirDroid the permissions needed:",
    Tip_NotPerm: "Seems like your device is not rooted. AirDroid requires root permissions to view and capture screenshots.",
    Tip_GettingRootPerm: "AirDroid is attempting to gain root permissions to view and capture screenshots.",
    Tip_screenshot: "Capture a screenshot",
    Tip_play: "Realtime",
    Tip_stop: "Stop realtime",
    Tip_fullscreen: "Enter full screen",
    RootTip_Root_A_3: "To capture a screenshot, AirDroid needs to access your Android's system-level interface.",
    RootTip_Root_Q_4: "Will the screenshot feature affect my Android system?",
    RootTip_Root_A_4: "No. AirDroid only performs read operations to capture screenshots.",
    tip: "Press [F11] to enter full screen mode. Press [ESC] to exit.",
    Msg_NotPerm: "Root permission required",
    Tip_networkspeed: "Seems like you are encountering a slow network connection.",
    RootTip_Root_A_1: 'Rooting is a process allowing users of mobile phones, tablet PCs, and other devices running the Android operating system to attain privileged control (known as "root access") within Android\'s subsystem. {0}Learn More{1}'
}, Airdroid.Lang.Desktop = {
    MenuItem_CloseAll: "Close all",
    MenuItem_Restore: "Restore",
    MenuItem_ShowDesktop: "Show desktop",
    MenuItem_Close: "Close",
    MenuItem_Min: "Minimize",
    MenuItem_Max: "Maximize",
    No_Frequent_Contacts: "Empty",
    LanConnectMode: "LAN Connection Mode",
    RemoteConnectMode: "Remote Connection Mode",
    LiteConnectMode: "You are now using Lite Mode. To enjoy the full AirDroid experience, please visit {0}web.airdroid.com{1}.",
    MenuItem_Lock: "Lock",
    Failed_To_Save: "Failed to save"
}, Airdroid.Lang.AudioPlayer = {
    Btn_Prev: "Previous",
    Btn_Next: "Next",
    Btn_Play: "Play",
    Btn_Pause: "Pause",
    Btn_Unmute: "Unmute",
    MI_RepeatOne: "Repeat current",
    MI_LoopOn: "Repeat all",
    NotSupportError: "Error",
    TypeNotSupport: "File type not supported.",
    Btn_Mute: "Mute",
    MI_LoopOff: "Repeat off",
    SupportDesc: "Failed to load the player. Please try to install Flash plugin."
}, Airdroid.Lang.Workspace = {
    LeftBar_More_MenuItem_Lock: "Lock",
    Message_ClearAllNotice: "Clear all notifications."
}, Airdroid.Lang.Photo = {
    ZipName_PhotoDefaultExportName: "Photos_downloaded_by_AirDroid",
    Message_SureToSetAsWallpaper: "Are you sure to set this picture as wallpaper?",
    Message_SetWallpaperSucceed: "Set as wallpaper success.",
    Message_SureToDeleteThisPhoto: "Are you sure to delete this photo?",
    Message_DeleteThisPhotoFailure: "Failed to delete this photo.",
    Label_CameraFolder: "Camera Roll",
    Label_WallpaperFolder: "Wallpaper",
    Message_SureToDeleteSelectedPhoto: "Are you sure you want to delete the selected photos?",
    Message_DeleteSelectedPhotoFailure: "Failed to delete the selected photos.",
    Last_Tip: "It's the last photo. Will go to first one if you continue."
}, Airdroid.Lang.Music = {
    ZipName_MusicDefaultExportName: "Music_downloaded_by_AirDroid",
    Label_Artist: "Artist",
    ToolTip_AlbumName: "Album:",
    ToolTip_AlbumArtist: "Artist:",
    ToolTip_SortBySongs: "List view ",
    ToolTip_SortByAlbums: "Grid view",
    MenuItem_SetAsPhoneRingtone: "phone ringtone",
    MenuItem_SetAsNotification: "notification ringtone",
    MenuItem_SetAsAlarm: "alarm ringtone",
    Message_SureToDeleteThisSong: "Are you sure you want to delete this song?",
    Message_DeleteSongFailure: "Fail to delete.",
    Message_SureToDeleteSelectedSongs: "Are you sure you want to delete the selected songs?",
    Message_DeleteSongsFailure: "Failed to delete the selected songs.",
    Message_AlreadyPhoneRongtone: "This song was already set as phone ringtone.",
    Message_AlreadyNotification: "This song was already set as notification ringtone.",
    Message_AlreadyAlarm: "This song was already set as alarm ringtone.",
    Message_SetPhoneRongtineFailure: "Failed to set new phone ringtone.",
    Message_SetNotificationFailure: "Failed to set new notification ringtone.",
    Label_Album: "Album",
    ToolTip_AlbumTracks: "Tracks:",
    MenuItem_SetAs: "Set as",
    Message_SetPhoneRongtineSucceed: "New phone ringtone set.",
    Message_SetNotificationSucceed: "New notification ringtone set.",
    Message_SetAlarmSucceed: "New alarm ringtone set.",
    Message_SetAlarmFailure: "Failed to set as alarm ringtone."
}, Airdroid.Lang.Ringtone = {
    TabName_Notification: "Notification",
    TabName_Alarm: "Alarm",
    ZipName_RingtoneDefaultExportName: "Ringtone_downloaded_by_AirDroid",
    Message_RingtoneInUse: "This ringtone is in use.",
    Message_SureToDeleteRingtone: "Are you sure you want to delete this ringtone?",
    Message_SureToDeleteSelectedRingtones: "Are you sure to delete the selected ringtones?",
    Message_DeleteRingtoneFailure: "Failed to delete this ringtone.",
    TabName_Ringtone: "Phone",
    Button_Set: "Set",
    Message_CanNotDelete: "Can't delete system ringtones."
}, Airdroid.Lang.Clipboard = {
    Message_ReadClipFromDeviceFailure: "Failed to read clipboard content from device.",
    Message_SendClipToDeviceFailure: "Failed to send clipboard content to device.",
    Message_SendToDeviceClipBoardSucceed: "Saved to device clipboard.",
    Button_ToDevice: "Refresh",
    Button_FromDevice: "Save",
    Message_ContentTooLong: "Error. Content too long.{0}{1} exceeded characters.",
    Input_PlaceHolder: "Clipboard"
}, Airdroid.Lang.TitleWidget = {
    Message_ReceivedMessages: "Receive {0} new message(s)"
}, Airdroid.Lang.About = {
    Label_Website: "<a target='_blank' tabname='AirDroid' href='http://www.airdroid.com'>http://www.airdroid.com</a>",
    Label_Help: "<a target='_blank' tabname='User Guide' href='http://www.airdroid.com/userguide.html'>http://www.airdroid.com/userguide.html</a>",
    Url_Facebook: "http://www.facebook.com/AirDroid",
    Url_Twitter: "http://twitter.com/AirDroidTeam",
    Url_Youtube: "http://www.youtube.com/user/AirDroidTeam",
    Url_Tumblr: "http://airdroid.tumblr.com/",
    Url_Googleplus: "http://gplus.to/AirDroid",
    Label_Copyright: "© 2014 Sand Studio",
    VScrollText_Main: "AirDroid is a fast, free app that lets you wirelessly manage & control your Android device from a web browser without cables.<br/><br/>Thanks to suggestions and assistance from:<br>Ramona Shelburne (US)<br>John Phillips (UK)<br>Turkdale (Turkey)<br>Peter Yang (China)<br>Anna Ringstrom (France)<br>Amy Norton (Germany)<br>Salynn Boyles (US)"
}, Airdroid.Lang.Battery = {
    Message_GettingLow: "The battery is getting low:",
    Message_Reminding: "or less remaining.",
    Message_ConnectCharge: "Please connect charger"
}, Airdroid.Lang.SMSTimeOffsetSetting = {
    Label_QuestionTitle: "Adjust the timestamp of incoming messages",
    Label_Explain: "Offset = correct timestamp - wrong timestamp",
    Select_MinSuffix: "minute(s)",
    Select_HourSuffix: "hour(s)",
    ButtonText_Save: "Save",
    MsgBox_SaveFailed: "Failed to save. Please retry.",
    MsgBox_Saved: "Saved. Refreshing now...",
    Label_Value: "Offset"
}, Airdroid.Lang.Transport = {
    Main_Button_OpenInDevice: "Open on device",
    OpacityTip_OpenURLSuccess: "Opened successfully. Please check on device.",
    OpacityTip_OpenURLFail: "Failed to open on device. Please retry."
}, Airdroid.Lang.Browser = {
    ToolTip_Back: "Back",
    ToolTip_AddTab: "New Tab",
    TabName_UserGuide: "User Guide",
    TabName_Facebook: "Facebook",
    TabName_Twitter: "Twitter",
    TabName_TeamBlog: "Blog",
    TabURL_AppUserGuide: "http://www.airdroid.com/userguide.html?name=apps",
    TabURL_SMSUserGuide: "http://www.airdroid.com/sms.html",
    TabName_NewTab: "New Tab",
    ToolTip_Forward: "Forward",
    ToolTip_ListAllTabs: "All Tabs"
}, Airdroid.Lang.Camera = {
    underDevTip: "The feature is currently under development. Please check back again later.",
    tip: "Press [F11] to enter full screen. Press [ESC] to exit.",
    Tip_stop: "Stop realtime",
    Tip_Photo: "Take a shot",
    Tip_networkspeed: "Your network is too slow currently",
    Tip_StopError: "Failed to close camera",
    Tip_fullscreen: "Enter full screen",
    Tip_reStart: "It seems that your camera is closed. {0} Try Restart{1}",
    Tip_StartError: "Failed to start camera",
    Tip_play: "Realtime"
}, Airdroid.Lang.FindMyPhone = {
    Custom_Phone: "{0}'s phone",
    Location_Time: "Location {0} minute(s) ago",
    Location_Date: "location {0} ",
    location_load: "Locating device...",
    Send_Pre: "The device is lost. Please call me.",
    Send_Tip: "Enter a message that will display with your phone number.",
    Send_Default: "Alert",
    Button_Cancel: "Cancel",
    Button_Confirm: "Confirm",
    Enter_Pwd_Error: "Passcode doesn't match.",
    Wipe_Title: "Wipe device",
    Wipe_Tip_Warning: "Warning: Your device will be reset to factory default! All personal data will be permanently deleted and can not be recovered!",
    Button_Continue: "Continue",
    Wipe_Sure_Tip: "Wipe device",
    Wipe_Pre: "Enter AirDroid password",
    Wipe_Data: "Wiping device data...",
    Confirm_Content: "Enter AirDroid password",
    Confirm_Required: "Enter AirDroid password",
    Confirm_Error: "Password is not correct",
    Error_Code_Offline: "Your Android device is not accessible at this moment.",
    Error_Code_Send_Fail: "Failed to send the message.",
    Error_Code_Wipe_Fail: "Failed to wipe data on the device.",
    Mask_Tip2: "Please enable this feature in AirDroid settings on your device and then {0}refresh{1}.",
    Login_Title: "Sign in again required",
    Phone_Tip: "Click to show operations",
    CAPS_Lock: "Caps Lock is on",
    Device_Offline: "Your Android device is not accessible at this moment.",
    My_Device: "My device",
    Send_loading: "Setting Lost mode...",
    Button_Send: "Send",
    Enter_Pwd: "Enter a passcode",
    ReEnter_Pwd: "Enter passcode again",
    Wipe_Tip: "Your device will be reset to factory default!  All personal data will be permanently deleted and can not be recovered. Are you sure you want to wipe all data?",
    Button_Wipe: "Wipe",
    Confirm_Title: "Alert",
    Error_Code_Lock_Fail: "Failed to lock the device.",
    Mask_Tip1: "Find Phone feature is not enabled on your device.",
    Login: "Sign in",
    Not_Find: "Failed to locate the device.",
    Airdroid_Password: "AirDroid password",
    Standard: "Standard",
    Satellite: "Satellite",
    Load_Wrong_Tip1: "Oops...something went wrong.",
    Load_Wrong_Tip2: "Click {0}here{1} to try again.",
    Low_Version_Tip: "Android version 2.1 and lower is not supported by Find Phone.",
    Hybrid: "Hybrid"
}, Airdroid.Lang.DialPad = {
    Call_Out_Tip: "Please proceed on device.",
    Button_Call: "Call",
    Button_Message: "Message",
    Add_Contact: "Add to contacts",
    Call_Ring_Title: "Incoming call",
    Call_Reject: "Reject",
    Call_Reject_Send: "Reject with message",
    Call_Out: "Calling",
    Call_Out_End: "End call",
    Call_Notice: "{0} missed call(s)",
    Call_Answer: "Connected"
}, Airdroid.Lang.AirTransport = {
    OpacityTip_OpenURLFail: "Failed to open on device. Please retry.",
    Message_ContentTooLong: "Error. Content too long.{0}{1} exceeded characters.",
    Input_PlaceHolder: "Clipboard",
    Url: "URL",
    Main_Button_OpenInDevice: "Open on device",
    OpacityTip_OpenURLSuccess: "Opened successfully. Please check on device.",
    Message_ReadClipFromDeviceFailure: "Failed to read clipboard content from device.",
    Message_SendClipToDeviceFailure: "Failed to send clipboard content to device.",
    Button_ToDevice: "Refresh",
    Button_FromDevice: "Save",
    File: "File",
    Clipboard: "Clipboard",
    Drag_Files: "Drag & Drop files or folders here",
    clear: "Clear",
    Proceed_Device: "Please proceed on device.",
    Upload_Success: "{0} succeeded",
    Upload_Faile: "{0} failed, {1} succeeded",
    Message_SendToDeviceClipBoardSucceed: "Saved to device clipboard.",
    Select_File: "Select file",
    App: "App",
    Update_To: "Upload to"
}, Airdroid.Lang.Welcome = {
    t1: "One less cable",
    t2: "Move things on and off your Android device without a USB cable. Even when the device is not nearby.",
    t3: "One less screen",
    t5: "One less worry",
    t6: "Locate and lock your Android when it’s lost. Cannot get it back? Simply wipe all data remotely.",
    t9: "Share the news",
    t10: "You’ve upgraded to AirDroid 2 Premium",
    t11: "Your free 2-month AirDroid 2 Premium membership is activated. Enjoy the full AirDroid 2 experience :-)",
    share_on: "Share on {0}",
    share_cnt: "Discover AirDroid 2, the best free app that lets you manage Android in web browser: {0}",
    t14: "Fly higher & longer",
    t19: "See through the lens of your Android device's camera remotely.",
    t20: "Dial remotely",
    t21: "Dial phone numbers remotely from the web and talk on the phone.",
    t22: "Remove promotions",
    t23: "As a premium user, you can remove promotion messages.",
    t25: "Connect up to 6 devices to 1 AirDroid account.",
    t28: "Go Premium",
    t4: "Send and receive SMS from your big-screen computer, without being distracted by the small-screen thing.",
    t7: "Get AirDroid 2 Premium for free!",
    t8: "Share AirDroid 2 on Facebook or Twitter and get 2-month premium membership for free. Limited time offer.",
    t12: "Start AirDroid 2 Premium",
    t13: "Failed, please try again.",
    t16: "Larger files",
    t17: "Transfer larger files (up to 100MB per file) in Remote Connection Mode.",
    t18: "Remote Camera",
    t24: "Multiple device support",
    t26: "Priority support",
    t27: "You’ll be sent to the front of the queue for faster support response.",
    t29: "Catch intruders",
    t30: "Take photos of people trying to unlock your device. Find Phone mobile: f.airdroid.com.",
    t15: "Up to 1GB data quota per month for Remote Connection Mode."
}, Airdroid.UsedLang = Airdroid.Lang;
