/**
 * Created by cwr.Yingsheng.Feng on 2014.11.23 0023.
 */
Airdroid.UsedLang = {}, Airdroid.Lang.Version = "1.1.0", Airdroid.Lang.Footer = {
    forum: "论坛",
    choose_title: "选择语言",
    nohas_lng: "非本国语言？",
    set_lng: "变更",
    language: "语言",
    Join_translate: "帮助我们将 AirDroid 翻译成您使用的语言",
    local_lng: "已安装",
    online_lng: "可用",
    donate: "捐赠",
    help: "帮助",
    contact: "联系人",
    verficate_code: "密码",
    about_us: "关于我们",
    security: "安全",
    privacy_policy: "隐私政策"
}, Airdroid.Lang.Login = {
    Option_SSL: "使用安全连接 (https)",
    Label_Version: "版本：",
    Message_RetryAfter: "AirDroid验证码已被禁用，{0}后恢复。",
    Message_NetworkError: "连接失败！请检查您的网络。",
    Message_AutoLoginInProgress: "自动登录中...",
    Not_LanNetwork: "连接失败！请确认您的设备与电脑已连接至同一个无线网络。",
    Cookies_Required: "您的浏览器上未启用Cookie，请在浏览器的设置中调整安全设置，启用Cookie后继续。",
    btn_OK: "确定",
    Msg_KickOut: "您的帐户已在其他地方登录,{0}您现在将被强制退出登录。",
    Tip_KickOut: "如果这不是您本人的操作，我们强烈建议立即更改密码来保护您的隐私。",
    Btn_LogInAgain: "请重新登录",
    Button_Login: "登录",
    Msg_Srv_Unavailable: "无法连接到设备。您可以排除以下原因后重试：",
    Msg_Srv_Unavailable_1: "检查您设备的网络连接是否正常",
    Msg_Srv_Unavailable_2: "唤醒或解锁您的Android设备",
    Message_Connecting: "正在连接设备...",
    Message_InputPassword: "请输入密码",
    Message_Locked: "已锁定，请输入密码解锁。",
    Message_AlreadyLogin: "您的帐户已在别处登录。"
}, Airdroid.Lang.Common = {
    Btn_Gotit: "知道了",
    Connecting: "设备无响应",
    Clear: "清除",
    ToolTip_Next: "下一张 [→]",
    notify_me_when_find: "找到时通知我",
    present_guest_error: "3. 有可能是您的Chromebook没有登录Google帐号，请登录后重试。",
    Setting: "设置",
    Reinstall: "重新安装",
    Message_Forbidden: "连接被重置，请手动重连设备。",
    NavBar_ShowDesktop: "显示桌面",
    NavBar_SpeedUpload: "快速上传",
    NavBar_NewMessage: "新信息",
    NavBar_MultipleDesktops: "多桌面",
    ToolTip_SetAsWallpaper: "设为壁纸",
    ToolTip_Prev: "前一张 [←]",
    ToolTip_RotateLeft: "向左旋转 [上键]",
    ToolTip_RotateRight: "向右旋转 [下键]",
    Open: "打开",
    NewFolder: "新建文件夹",
    Refresh: "刷新",
    Paste: "粘贴",
    Copy: "复制",
    Delete: "删除",
    Export: "下载",
    Install: "安装",
    ZipedAndExport: "以 ZIP 格式下载",
    LoadingMore: "更早的信息",
    Server_Stop: "设备上的AirDroid服务已停止。",
    Label_SizeColumn: "大小",
    Label_TypeColumn: "类型",
    Label_FormatColumn: "格式",
    Label_ModifyDateColumn: "修改日期",
    ToolTip_Name: "名称：",
    ToolTip_Time: "时长：",
    ToolTip_Size: "大小:",
    ToolTip_FileLocation: "位置：",
    Tip_ListView: "列表视图",
    Button_Cancel: "取消",
    msg_SameFileName: "名称未更改。",
    msg_FileNameIsNull: "与之前的名称重复",
    msg_FileNameExist: "名称已存在，请更换一个。",
    Msg_AppConfigNotFound: "配置文件未找到",
    InputDefaultText_Search: "搜索",
    TipText_Call: "呼叫",
    TipText_Forward: "转发",
    ToolTip_Share: "分享",
    Continue: "继续",
    Msg_NotWifiNetWork: "AirDroid当前正在使用移动设备的网络连接，要节约设备的数据流量，请尝试将您的设备连接到WiFi网络。",
    Back: "返回",
    Search: "搜索",
    Search_For: "搜索",
    Share_Success: "成功",
    Share_To: "分享到{0}",
    Emoticon: "表情符号",
    Emoji: "颜文字",
    Add: "添加",
    Folder_Contact: "文件夹快捷方式",
    Shortcut_Contact: "联系人快捷方式",
    Desktop_folder: "文件夹",
    File_System: "Android的文件系统",
    Devices: "设备",
    Languages: "语言",
    Contact_us: "联系我们",
    Move_To: "移动到",
    Workspace: "工作区",
    Folder_Del_Alert_1: "请先将文件夹中的应用模块移除再删除。",
    Folder_Del_Alert_2: "这个操作将删除文件夹中的所有内容，确定要继续吗？",
    UserName: "用户名称",
    KeepLogin: "两周内保持登录",
    Already_have_account: "登录",
    Authenticating: "正在验证身份信息...",
    PasswordIncorrect: "输入的帐号或者密码不正确。",
    UserNameIncorrect: "邮箱地址不正确",
    Connecting_To_Device: "正在连接设备...",
    Failed_To_Conn_Device: "未能连接到设备",
    Connect_Twiiter_reg: "使用Twitter账户注册此用户名进行连接",
    Change_Diff_UserName: "昵称重复",
    SignUp: "注册",
    Yes: "是",
    No: "否",
    UserNameValidateMsg: '只能使用字母、 数字和"_"（下划线）的组合',
    PasswordValidateMsg: "密码必须是包含数字和字母的至少8个字符的组合",
    ConfirmPwdValidateMsg: "密码不匹配",
    EmailValidateMsg: "请输入一个有效的电子邮件地址",
    EmailExist: "此电子邮件地址已被注册",
    Enter_Nickname: "请输入昵称",
    Enter_NewPassword: "请输入一个新密码",
    ModifyProfileSuccess: "修改成功",
    NavBar_SpeedInstall: "快捷安装",
    NavBar_Setting: "设置",
    SelectAll: "全选",
    Import: "上传",
    Cut: "剪切",
    Play: "播放",
    Rename: "重命名",
    Download: "下载",
    NewSms: "新信息",
    Message_NetWorkError: "啊哦~您的网络好像有些问题哦~",
    Label_NameColumn: "名称",
    Label_TimeColumn: "时长",
    ToolTip_FolderName: "文件夹:",
    ToolTip_PhotosCount: "照片: ",
    ToolTip_Duration: "时长:",
    ToolTip_CreateDate: "日期:",
    Tip_GridView: "网格视图",
    Button_Close: "关闭",
    Button_Ok: "确定",
    Alert_Title: "警告",
    msg_FileHasIllegalCharacter: '不支持以下字符:  / : * ? " < > ,| &',
    Message_LoadAppsConfigError: "无法加载配置文件！请单击“确定”重新登入。",
    Msg_AppsConfigNotLoaded: "无法加载配置文件",
    InputDynamicText_Search: "搜索应用",
    CategoryCountSuffix_Items: "条目",
    TipText_Edit: "编辑",
    Loading: "加载中...",
    No_Search_For: "没有结果",
    Shared_Via_Airdroid_Facebook: "通过AirDroid分享",
    Shared_Via_Airdroid_Twitter: "通过AirDroid分享",
    Share_Faile: "失败",
    Logout: "注销",
    Account: "帐户",
    About: "关于",
    Password: "密码",
    Or_You_May_QR: "扫描二维码",
    Register: "注册",
    Enter_User_Password: "请输入密码",
    isCheck: "检查中",
    Failed_To_Signin: "登录失败",
    Signin: "登录",
    AreYou: "你是",
    ModifyProfileFail: "修改失败",
    Call_Out: "呼叫",
    UnbindFailed: "解除绑定失败",
    NickName: "昵称",
    Connect: "连接",
    Disconnect: "断开连接",
    OldPasswordIncorrect: "当前密码输入不正确",
    NewPwdEqualOldPwd: "密码没有更改，请重试。",
    RegFailded: "注册失败。",
    UnbindSuccess: "解除绑定成功",
    NewPassword: "新密码",
    Email: "电子邮件",
    OldPassword: "当前密码",
    ConfirmPassword: "确认密码",
    Save: "保存",
    Connected: "已连接到 {0}",
    Bind: "绑定",
    NotBound: "没有已连接的设备。",
    FileLinkExisted: "已经有此文件夹的快捷方式。",
    Power_Saving_Tip: "您的AirDroid已经长时间处于非活动状态，进入省电模式，服务停止。如果不希望进入省电模式，您可以在AirDroid设置项中关闭。",
    UnboundS1: "在您的设备上安装 AirDroid。",
    UnboundS2: '在设备上打开 AirDroid 并点击"帐户"按钮。',
    QrNotSameWifiNoAccount: "除非设备和计算机在相同的WiFi网络中，否则要通过二维码登录，需要在设备上绑定帐户。",
    UseAccountLogin: "登录帐户",
    TwitterAuthNameError: "您的twitter帐户名不匹配{0}。请再试一次。",
    EditContact_Success: "编辑联系人图标成功。",
    RequireLogin: "您需要创建一个帐户，才能使用此功能。",
    RequestToAuth: "请在设备上点击“接受”以建立连接。",
    Send_Message: "发送消息",
    Find_Phone: "寻找手机",
    SureToExitAndCloseTab: "你真的想要退出并关闭此页吗？",
    UserCenterTabTip3: "连接 SNS 帐户方便与您的朋友共享信息。注意：您登录时所使用的第三方帐户不能取消关联。",
    ConnectWith: "连接到 {0}",
    Change: "更改",
    NotBoundDevice: "这个帐号还没有绑定设备呐~",
    UserNameExist: "哎呀，用户名被占用了，换一个吧~",
    UnboundS3: "登录帐号之后刷新本页面。",
    ProgramProcess: "正在加载应用程序资源...",
    Checking: "验证中",
    SureToExit: "确实要注销吗？",
    UserCenterTabTip1: "电子邮件地址将用于恢复您的密码。",
    UserCenterTabTip2: "强烈建议使用高强度密码，以更好地保护您的帐户安全。",
    Thief_Tip1: "永远不会再次失去你的手机 ！",
    desktop_sound: "消息声音提醒",
    ChangeLangTip: "重新登录AirDroid后生效",
    Flow: "流量使用情况",
    FlowRemain: "剩余流量: {0}",
    Contact_Tip: "AirDroid目前仍在早期的 beta 测试。为了控制我们的成本，您每月有 {0} 流量使用配额。如果您需要更多，请联系我们。我们可能会在之后增加您的流量。",
    Forgot_Password: "忘记密码?",
    Login_With: "使用以下帐号登录",
    LostMode: "丢失模式",
    Thief: "入侵者",
    FindPhone_Num_Tip: "输入一个可以联系到您的电话号码，它会显示在丢失的设备上。",
    Button_Next: "下一步",
    Thief_Tip3: "此功能即将推出。",
    Drag_APK: "拖放APK文件到这里",
    fill_require: "所有信息都是必填的",
    rotate: "旋转",
    placard: "通知",
    see_all_placard: "查看所有通知",
    no_placard_tip: "没有通知",
    Searching_for_Device: "正在查找设备",
    closing_camera: "关闭摄像头",
    forgot_password: "忘记密码?",
    login_with: "使用以下帐号登录",
    NoDeviceTip1: "此帐户未绑定设备",
    start_camera_error: "启动摄像头失败。请在设备上退出照相机或者{0}重试{1}。",
    Need_Premium: "此功能只向高级用户开放，你想要升级为高级用户吗？",
    account_type: "用户类型",
    mem_since: "用户资格",
    usage_month: "流量使用情况",
    upgrade_title: "升级到高级用户",
    upgrade_des: "获得终极的AirDroid体验。",
    free: "免费用户",
    premium: "高级用户",
    first_camera_tip: "使用相机功能时，AirDroid需要独占您手机的照相机，在此期间您将无法在手机上使用照相机进行拍照。",
    DataFlowNotAbleToUpload_P: "您的远程数据流量已用完，您可以使用局域网方式连接来继续使用AirDroid或者购买更多的远程数据流量。",
    RemoteMode_FileTooLarge_F: "普通用户在远程连接模式下传输单个文件的大小不能超过 {0} MB 。若要传输较大的文件，请在同一Wifi下使用 AirDroid，或者升级为高级用户(单个文件传输大小可增加到{1}MB)。",
    How_To_Sign_Up_Title: "如何注册AirDroid帐户？",
    How_To_Sign_Up_S1: "扫描二维码或 <a href='{0}' target='_blank'>点击这里</a> 安装Airdroid 2.",
    How_To_Sign_Up_S2: "在设备上的Airdroid中注册一个帐户并登录。",
    Change_Email_Address: "更改电子邮件地址",
    Confirm_Email: "确认邮箱",
    Change_Email: "更改邮箱",
    phone_location_close: "您的设备未开启定位功能，Find Phone可能无法定位您的设备。",
    ZoomIn: "放大",
    ScanQRCodeToInstall: "扫描二维码来安装",
    search_key_title: "按短信内容搜索",
    incoming_call: "{0}的电话",
    notification_call_title: "新来电",
    message_to: "收件人：",
    add_contact: "添加到联系人",
    check_contact: "查看联系人",
    new_message: "新建短信",
    new_message_to: "新建短信",
    close_desktop_notification: "关闭桌面通知",
    QCC_Confirm_payment: "请确认支付结果",
    QCC_Tip_2: "支付业务：增加1GB的远程数据流量",
    QCC_Tip_3: "支付完成前请不要关闭此窗口",
    QCC_BTN_2: "重新购买",
    QCC_Fail_1: "银行/账户已扣款，但没有提示成功？",
    QCC_Fail_2: "网络传输问题可能造成延时，请不要担心，我们会尽快和支付渠道对账后，完成此交易。",
    QCC_Fail_3: "银行/账户没有扣款？",
    upgrade_title1: "需要更多远程数据流量？",
    QCC_Tip_7: "本月购买的流量仅能在本月高级帐户期限内使用；",
    total: "总计",
    Price: "金额：",
    QCC_Fail_4: "建议您重新支付一次试试看，如果仍无法成功，请联系PAYPAL或相关银行的客服。",
    Increase_Quota: "提高数据流量",
    Button_Previous: "上一页",
    uninstall_app_tip: "请到设备上确认卸载。",
    check_find_phone: "正在检查AirDroid是否有开启寻找手机服务...",
    connect_1: "正在查找设备...",
    connect_3: "正在智能判断您的网络...",
    connect_4: "正在以局域网模式连接您的设备...",
    connect_5: "正在以远程模式连接您的设备...",
    connect_6: "成功找到您的设备",
    connect_7: "唤醒成功",
    connect_8: "唤醒失败",
    connect_12: "连接设备成功",
    connect_13: "连接设备失败",
    operate_fail: "操作未成功，暂不支持您的设备",
    connect_14: "网络检查完成",
    LiteConnectMode_tip: "若设备上的连接请求界面未出现，请稍等一会",
    ConnFAQ: "仍然不能连接吗？查看更详细的帮助。",
    delete_account: "停用帐户",
    delete_account_msg: "如果您需要任何帮助，可以直接联系我们： {0} support@airdroid.com {1}。",
    tell_why: "请告知我们您离开的原因",
    opt_select_a_option: "请选择一个选项",
    opt_change_email: "我想换一个邮箱注册",
    opt_unbind_sns: "我想解除SNS帐号的绑定",
    delete_failure_try_later: "未能停用您的帐户，请稍后重试。",
    tip_reason_null: "请选择您离开的原因。",
    tip_reason_change_email: "您可以直接在AirDroid中{0} 更换邮箱 {1}",
    item_1: "项目：AirDroid高级会员1个月",
    item_3: "项目：AirDroid高级会员2年",
    usepaypal: "*通过PayPal（贝宝）付款",
    Pay_w: "项目",
    Pay_o: "订单号",
    Pay_p: "付款方式",
    Pay_t1: "仅显示24个月内的购买记录",
    Pay_t3: "所有价格均含税",
    select_group: "选择群组",
    create_success: "创建成功",
    edit_success: "保存成功",
    edit_failed: "保存失败",
    sure_delete_group: "是否确定要删除群组 {0}?",
    group_name_null: "请输入群组名称",
    new_group_label: "新建群组",
    click_detail_contact: "点击左侧的联系人显示详细信息",
    label_blog: "博客",
    label_ftp: "FTP",
    label_website: "网站",
    add_group: "新建群组",
    contact_need_tip: "姓名和电话号码不能为空",
    confirm_save_contact: "是否保存对联系人信息的修改？",
    Pay_total: "总计",
    group_repeat: "该群组名称已经存在",
    premium_renewals: "延长服务期限",
    premium_expire_tip: "您的高级帐户服务到期日期：{0}",
    premium_extend: "延长服务期限",
    payment_account_success: "支付完成，成功升级为高级帐户。",
    no_thieves_found: "没有入侵者数据：",
    cancel_autopay: "取消订阅",
    success_cancel_autopay: "您已经成功取消高级帐户服务订阅",
    find_my_phone_instruction: "帮助",
    no_thief_tip1: "您的设备需要加密码锁（用系统设置中的密码锁加锁或者AirDroid丢失模式加锁）",
    no_thief_tip2: "当有人尝试解锁您的设备，密码输入错误后，AirDroid会启动前置摄像头拍下他的照片传回并定位他的位置。",
    get_device_location_failure: "获取位置失败",
    add_to_desktop: "添加到桌面",
    delete_from_desktop: "从桌面删除",
    load_again: "请 {0}单击这里 {1} 重新加载",
    normal: "一般",
    desktop_notification: "桌面通知",
    email_subscription: "电子邮件",
    "default": "设为默认",
    email_tip1: "新功能通知",
    email_tip2: "促销信息",
    add_desktop_success: "已成功添加",
    remove_from_desktop_success: "已成功删除",
    connect_stop_tip: "与设备的连接已中断，请检查网络后重新连接",
    connect_device_error: "无法连接设备，请检查网络。",
    reconnect_expired: "您的手机已经断开太长时间，为了保障您手机的安全，需要您重新登录帐号才能连接手机。",
    email_success_tip1: "验证邮件已经发送到您的邮箱：{0}，请查收邮件。",
    click_new_contact: "点击“新建联系人”来创建新的联系人",
    send_email_timer: " {0}s 后可以重新发送",
    need_connect_device: "操作失败。您的设备已经断开连接，请重连后再操作。",
    item_4: "项目：AirDroid高级会员1个月 - 体验套餐",
    select_pay_mode: "请选择一个会员方案",
    select_pay_mode_tip: "升级为AirDroid高级会员，可以享受AirDroid提供的所有高级服务。",
    premium_cancel_autopay: "到期后自动续费(勾选后可在“个人中心”中取消)",
    premium_feature_list_title: "高级会员专享",
    label_month: "月",
    label_year: "年",
    label_years: "{0} 年",
    premium_year_des: "免费赠送1年，总共可享受3年高级服务",
    premium_icon_hot: "最热门",
    premium_icon_value: "最划算",
    connect_device_name_tip: "正在连接到{0}，请稍候...",
    select_default_device_tip: "下次登录默认连接这台设备",
    select_your_device: "请选择一台设备",
    select_a_device: "请选择一台设备",
    select_a_device_tip: "您的帐户现在绑定了{0}台设备，免费用户只能绑定一台设备，升级为高级用户后可以继续绑定多台设备，若您不升级，请选择一台要绑定的设备，其他设备将会取消绑定。",
    unbind_device_success_tip: "解除绑定成功！",
    unbind_device_fail_tip: "解除绑定失败，请重试！",
    add_devices: "添加设备",
    add_more_devices: "增加更多设备",
    unbind_device_tip: "您现在正在取消绑定设备：{0}，为保证您设备的安全，需要输入您的帐户密码来取消绑定。",
    bind_more_tip: "若要添加新设备，请在新设备上登录当前的AirDroid账号",
    unlock: "解锁",
    unlock_tip: "使用此功能将会清除设备上的锁屏密码，确定要清除吗？",
    wipe_premium_tip: "可以使用AirDroid将手机恢复为出厂设置，擦除隐私数据，以保护数据安全。",
    present_t1_content: "仅提供给Samsung Chromebook 2使用，由Samsung和AirDroid共同赞助。",
    present_t2_check_eligibility: "正在验证领取资格，请稍候...",
    present_t3_success_content: "恭喜您，成功升级为AirDroid 高级会员",
    present_t4_fail_content: "领取失败，原因可能是：",
    present_t4_fail_tip1: "1. 您已经在这台设备上领取过礼包",
    present_t5_about: "什么是AirDroid？",
    present_t5_intro_title1: "省一条线缆",
    present_t5_intro_content1: "不用数据线，在电脑和设备之间传输任何文件",
    present_t5_intro_title2: "省一块屏幕",
    present_t5_intro_title3: "省一份担心",
    present_t5_intro_content3: "定位找回丢失的设备",
    present_t6_retry: "重试",
    present_server_error: "连接服务器失败，请先检查网络，再点击“重试”重新领取。",
    present_login_signUp: "注册",
    present_login_signWith: "使用以下帐号登录",
    present_loginBefore_btn: "登录领取",
    present_loginAfter_btn: "领取",
    email_verify: "邮箱未验证，立即验证",
    email_verify_tip: "邮箱未验证",
    set_external_sdcard_tip: "如果AirDroid无法识别您的SD卡，请手动选择SD卡路径：",
    set_external_sdcard: "添加外部SD卡",
    delete_external_sdcard_tip: "确定要移除此SD卡目录吗？",
    switch_device_label: "切换设备",
    delete_file: "删除文件",
    android_version_no_support_tip: "AirDroid2.0.7及更高版本将不再支持Android 2.1及以下系统，您可以继续使用现有版本。",
    default_replace_user_des: "使用系统默认的配置文件时，本次对桌面ICON的顺序调整、桌面快捷方式建立等个人配置不会被保存，但是不影响其他功能的正常使用。",
    use_default_appconfig: "使用默认配置文件",
    add_device_title: "您的帐号没有绑定设备",
    save_to_pc: "存储到电脑",
    click_to_choose_external_sdcard: "点击选择SD卡目录",
    camera_save_to_phone_success: "照片保存成功",
    server_network_error_tip: "访问服务器失败，请{0}重试{1}",
    keep_device_tip: "选择想保留的设备(最多2台)：",
    premium_expire_title: "高级帐户已到期",
    lights_on: "打开闪光灯",
    lights_off: "关闭闪光灯",
    device_nickname: "设备名称",
    pay_success: "付款成功",
    pay_fail: "付款失败",
    pay_type_code: "激活码 - {0}",
    save_percent: "节省 {0}",
    lable_or: "或",
    scan_qr_tip: "扫描二维码下载",
    free_user_add_device_tip: "您现在不是高级用户，一个帐户只能绑定两台设备，升级为高级用户后，同一个帐号可同时绑定6台设备。",
    reserve_attach_confirm: "上传的附件有一周的有效期，一周后，附件会自动失效。",
    fail_to_upload: "文件上传失败",
    attach_amount_limit: "每条短信只能发送一个附件。",
    cancel_all: "全部取消",
    cut_file_success: "剪切成功",
    drag_drop_or_click_to_upload: "将要上传的文件或文件夹拖放到此处",
    label_forgot: "忘记密码",
    device_set_default: "登录时默认连接的设备",
    mark_all_read: "全部设为已读",
    delete_account_msg2: "我们很遗憾您要离开！",
    no_default_device: "选择设备",
    video_fluency_tip: "载入速度及播放的流畅度与网络质量相关，网络较慢时可能需要等待较长时间。",
    release_to_beta_tip: "我们发现您手机上安装的是Beta测试版，将为您跳转到Beta测试地址。",
    Msg_Srv_Unavailable_3: "若电脑和Android设备在同一个局域网，可使用IP访问Android设备。",
    cancel_desktop_notification: "如果您已经在您的Chrome设置中禁用AirDroid桌面通知，您可以重新启用它。",
    Lite2Web_title1: "充分利用 AirDroid",
    Lite2Web_desc1: "您正在使用 Lite 模式。完整版本请访问 {0}。",
    SNS: "社交网络",
    chromebook_question: "如果有任何疑问，请将您的设备型号通过邮件发送给我们：support@airdroid.com，我们将在核对后给您回复",
    contact_no_name: "(无姓名的联系人)",
    Enter_User_Name: "请输入帐户名称",
    Enter_Email: "请输入电子邮件",
    Enter_OldPassword: "请输入当前密码",
    ChangePwdFail: "更改密码失败。",
    UsernameUsedOnTwitter: "此用户名在Twitter上已存在",
    ContactLinkExisted: "已存在此联系人的快捷方式",
    Account_Logout_Tip: "您的帐号在设备上已经注销，服务已停止。",
    RequestRefused: "连接请求被拒绝！{0}您可以刷新此页面并重试。",
    MonthDataFlowOverage: "您本月的远程数据流量已用完，本月内您不能再通过远程连接模式使用AirDroid。",
    FlowTip: "本月流量使用情况",
    FlowRecover: "在 {0} 天后重置流量",
    How_To_Sign_Up: "如何注册？",
    Input_Optional: "可选",
    Tip_Number: "电话号码",
    Thief_Tip2: "当您的手机丢失时，若有人尝试解锁您的手机且解锁失败，AirDroid将会启动前置摄像头拍下解锁者的照片并传回来。",
    adjusted_registration_tip: "我们已经调整注册过程以带给您更好的体验。用户名已经从AirDroid2中移除，您只能使用电子邮件和密码来登录。",
    continue_use_oldversion: "暂不升级",
    two_passwords_dont_match: "邮箱地址不匹配",
    not_change: "新邮箱与当前邮箱相同",
    change: "切换",
    no_support_camera: "您当前的Android版本（2.2 或更低）不支持该功能。",
    placard_read: "标记为已读",
    placard_detail: "详细信息",
    NoDeviceTip2: "请先在需连接的设备中登录帐户再继续操作",
    Remote_Need_Premium: "远程连接模式下，此功能只有高级用户才能使用，您要升级为高级用户吗？",
    Free_User_Overage_Tip: "您的远程数据流量已用完，您可以使用局域网方式连接来继续使用AirDroid或者升级为高级用户获取更多的远程数据流量。",
    Upgrade_to_Premium_User: "升级到高级用户",
    Premium_User_Overage_Tip: "您的远程数据流量已用完。",
    How_To_Sign_Up_S3: "用同样的帐户在web端登录。",
    New_Email: "新邮箱",
    google_server_unable: "定位服务不可用或者因为其他未知的原因，Find Phone可能无法定位到您的设备。",
    ZoomOut: "缩小",
    login_with2: "通过{0}登录",
    Update_Beta_Title: "AirDroid发布新版啦！",
    or: "或",
    Update_Beta_Title2: "AirDroid发布新版啦，建议您升级到最新版本享受更稳定的服务。 {0} 立即下载 {1}",
    search_name_title: "按联系人搜索",
    notification_message_title: "新短信",
    open_desktop_notification: "开启桌面通知",
    account_setting: "设置",
    QCC_Tip_1: "请您在新打开的页面完成支付！",
    QCC_Tip_4: "付款成功后，点击“支付成功”或关闭此窗口完成购买流程。",
    QCC_FailTitle: "支付未成功，请确认您的账户是否扣款！",
    QCC_Fail_5: "如果还需要帮助，您可发邮件至: pay@airdroid.com",
    "1gbExtra_add_success": "您的帐户已经成功增加了1GB的远程数据流量。",
    QCC_BTN_1: "支付成功",
    upgrade_des1: "只需$1.99，便能增加1GB的远程数据流量，可用于在远程访问手机时的任何操作",
    QCC_Tip_5: "增加1GB的远程数据流量",
    QCC_Tip_6: "仅需$ 1.99再获取1GB的 远程数据流量。",
    QCC_Tip_8: "您购买的流量有效期至 {0}（剩余{1}天）。",
    phone_auth_failed: "连接设备时出现异常（错误码：10001），请重试。",
    Update_1x_Title2: "AirDroid发布新版啦，建议您升级到最新版本享受更稳定的服务。 {0} 立即下载 {1}",
    install_app_tip: "请到设备上确认安装。",
    connect_2: "正在唤醒设备...",
    connect_9: "您的网络连接模式：局域网模式",
    connect_10: "您的网络连接模式：远程模式",
    connect_11: "数据连接已建立",
    ReConnect: "重新连接",
    tell_detail: "愿意详细说明一下吗？(可选)",
    opt_dont_want_to_use: "我不想用AirDroid了",
    opt_have_other_account: "我有另一个AirDroid帐号",
    other: "其他",
    delete_success: "帐户已成功停用",
    item_2: "项目：AirDroid高级会员1年",
    Pay_t: "付款",
    Pay_d: "日期",
    Pay_t2: "退款记录不会显示在购买历史中",
    operate_success: "保存成功",
    edit_group_label: "编辑群组",
    sure_delete_contacts: "确定要删除这些联系人吗？",
    label_homepage: "主页",
    add_field: "添加其他项",
    label_profile: "帐户",
    label_address: "地址",
    group_name_label: "群组名称",
    no_purchase: "无购买记录",
    upgrade_premium: "升级为高级帐户",
    go_premium: "升级高级帐户",
    cancel_autopay_tip: "取消订阅后，本次高级功能服务到期后，将会自动将您的帐户降为免费帐户。取消后您仍然可以到个人中心进行订阅。",
    sure_to_cancel: "确定要取消吗？",
    Thief_Tip4: "高级帐户才能享有此项服务，是否立即升级为高级帐户？",
    geocode_device_location_failure: "位置解析失败",
    Message_LoadUserConfigError: "无法加载配置文件！请单击“确定”重新登入。",
    lab_tip1: "AirDroid 实验室是新功能的试验场。当新功能已经为公众测试做好准备时，我们会逐渐放出这些功能。",
    lab_tip2: "所有在实验室里的功能都是临时性的，他们随时可能取消或终止。",
    label_reconnect: "重新连接",
    connect_device_tip: "正在连接设备...",
    loadErrorTip: "加载失败，请检查网络后重试。",
    labT1: "功能",
    labT2: "要求",
    email_verify_fail: "邮件发送失败，请稍后重试。",
    sending_email: "正在发送...",
    premium_month_des: "体验1个月，每月可使用1GB远程流量",
    sms_cannot_delete_tip: "抱歉，删除短信暂时不支持Android 4.4。",
    cancel_default_device: "取消默认连接",
    connect_other_device: "连接其他设备",
    label_choose: "连接",
    switch_device: "切换设备",
    default_connect_device: "默认连接设备",
    unlock_success_tip: "设备上的锁屏密码已经清除！",
    switch_update_tip: "您要连接的设备上安装的AirDroid不是最新版本，请先升级；若您要继续使用旧版，请点击“暂不升级”。",
    unlock_failed_tip: "锁屏密码清除失败！",
    present_t1_about: "AirDroid是什么？",
    present_t1_theme: "AirDroid高级用户礼包",
    present_t3_success_expire: "会员期限：{0}",
    present_t4_fail_tip2: "2. 您的设备不是三星Chromebook",
    present_t5_about_description: "AirDroid: 一款免费的安卓设备管理工具，不需要连接数据线，实现电脑与手机间的文件传输、快捷发送短信、找回丢失设备等。",
    present_t5_about_learnMore: "了解更多",
    present_t5_intro_content2: "大屏幕大键盘更高效发短信",
    present_login_skip: "跳过",
    present_start_airdroid: "开始AirDroid",
    default_replace_user_tip: "加载您的个人配置文件失败，您可以选择使用系统默认的配置文件，或者尝试重新加载。",
    label_reload: "重新加载",
    save_to_phone: "存储到设备",
    screenshot_save_to_phone_success: "截屏保存成功",
    premium_down_des: "您的高级帐户已经到期，同一个帐户同时只能管理2台设备，请选择您要保留的2台设备，或者升级为高级用户继续管理更多的设备。",
    apk_decode_error: "解析程序包时出现问题。",
    pay_status: "状态",
    lights_on_fail: "打开闪光灯失败",
    UnboundTitle: "您的帐号没有绑定设备，请按以下操作提示绑定设备：",
    UnboundS4: "在您的设备上{0}安装 AirDroid{1}。",
    input_site_name_and_url_please: "请输入网站名称和网址",
    share_services: "第三方帐号绑定",
    attach_size_limit: "上传文件不能超过10M",
    copy_file_success: "复制成功",
    attach_past_due: "文件已过期",
    label_verify: "已验证",
    device_number_tip: "您的帐号共绑定了{0}台设备",
    camera_fluency_tip: "真实的摄像帧数会受一些因素的影响，比如网络质量，相机像素和设备的其它配置。",
    beta_to_release_tip: "我们发现您手机上安装的AirDroid为正式版，将为您跳转到正式版使用，您也可以加入我们的G+社群申请成为内测人员。",
    notification_set_setp1: "点击Chrome浏览器地址栏左侧“查看网站信息”按钮，如图：",
    notification_set_setp2: "在下拉菜单中找到”通知”，选择“在此网站上始终允许”即可，如图：",
    Lite2Web_title3: "查找手机和保护数据",
    Lite2Web_desc3: "定位您的手机，并在无法拿回时擦除所有数据。",
    Lite2Web_title4: "连接您的所有 Android 设备",
    Lite2Web_desc4: "将您的所有 Android 设备连接至同一帐户。",
    Lite2Web_desc2: "通过任何网络远程访问您的 Android 设备。",
    Lite2Web_title2: "本地或远程网络",
    How_to_set_notication: "点击这里查看如何在其他浏览器上开启桌面通知功能。",
    upload_Permission_Denied: "上传失败，没有权限对SD卡进行写入操作。",
    upload_network_error: "上传失败，网络错误。",
    pop_window_disabled_des: "弹出窗口被浏览器拦截，请在浏览器中允许web.airdroid.com的弹出窗口后，再点击“OK”以继续。",
    change_path: "更改上传文件的存放路径",
    delete_thief_confrim: "确定要删除这条记录吗？",
    url_link_exist: "名称不能重复",
    flash_player_update: "你的浏览器的Flash Player版本太低，不支持AirDroid服务，请升级至最新版本",
    browser_nosupport_title: "你的浏览器版本太低，不支持AirDroid服务，请升级到IE8及以上版本，或使用以下浏览器",
    PlaySound: "响铃",
    mem_tip: "{0}天剩余",
    attach_load_fail: "文件无法加载",
    delete_thief_fail: "删除失败",
    click_to_choose_path: "点击选择路径",
    MainAccount: "注册帐号",
    external_sd_might_be_limited: "外置SD卡可能被限制",
    external_sd_might_be_limited_detail: "该设备上运行着Android 4.4 KitKat，并且挂载了外置SD卡。谷歌在Android 4.4 KitKat上添加了新的限制：不允许第三方应用在外置SD卡上进行写入操作。所以在部分运行KitKat的设备上，可能无法在外置SD卡上进行上传、剪切、删除文件/文件夹，新建文件夹等操作。",
    open_desktop_sound: "短信/电话来时有声音提醒",
    NavBar_Dashboard: "小工具",
    find_phone_connect_fail: "无法连接您的设备，可能是您的设备当前未连接到互联网。",
    present_need_login: "等待时间太长？请检查您的Chromebook是否有登录Google帐号。"
}, Airdroid.Lang.SSLTip = {
    Btn_Donotremind: "不再显示",
    Tip_SSLCommon: "安全超文本传输协议 (HTTPS) 提供加密的通信和安全认证。您的浏览器可能会显示一条警告，您可以放心地忽略它。因为 AirDroid 使用的是自签名证书，因此会出现此消息。示例：",
    Tip_Chrome: "当您在第一次使用「安全」方式登录时，Google 浏览器会显示一个「网站安全证书不可信任！」的警告，请点击「继续执行」来继续。",
    Tip_FFStep1: "如果使用安全连接选项，在第一次登陆的时候，Firefox 会显示一个标题为“该连接不可信任”的警告。点击“我知道风险”，然后点击“添加例外”。",
    Tip_FFStep2: "点击“确认安全例外”以继续。",
    Tip_Safari: '当您在第一次使用「安全」方式登录时，Safari浏览器可能会显示「Safari 无法验证网站"xxx"的身分。」的警告，请点击「继续」来继续使用 AirDroid。',
    Btn_Gotit: "明白了。"
}, Airdroid.Lang.SMS = {
    ToolTip_Call: "呼叫",
    Chat_MoreMessage: "更多信息",
    ContactSelectorDefault: "选择自定义群组...",
    MIUI_SMS_Line1: "请在您的设备上点击“允许”以授予AirDroid发送短信所需要的权限，然后再次发送。",
    MIUI_SMS_Line2: "如果您的 Android 设备上没有出现提示信息，请到您的权限管理程序（如超级用户）手动授予 AirDroid 短信权限。",
    Message_MultiChatTaskItem: "会话 ({0})",
    TimestampTip: '信息的时间显示不正确？请点击"设置"来更正。',
    Message_ContactInfoSaveSucceed: "联系人信息已保存。",
    Message_ContactInfoSaveFailure: "未能修改联系人。",
    Message_CreateContactInfoSucceed: "联系人创建成功。",
    Message_CreateContactInfoFailed: "创建联系人失败。",
    Message_ReadContactInfoFailed: "加载联系人信息出错。",
    Message_SureToDeleteCallLog: "确定删除此通话记录吗？",
    Message_Loading: "加载中...",
    Message_SmsSendSucceed: "信息发送成功。",
    Message_SureToDeleteSelectedThread: "确定要删除所选的内容吗？",
    Message_LoadGroupsFailure: "未能加载群组。",
    Message_LoadCallLogsFailure: "未能加载通话记录。",
    Message_DeleteCallLogFailure: "删除此通话记录失败。",
    CallLog_Lable_TypeColumn: "呼叫",
    CallLog_Lable_TimeOfCalls: "时间",
    CallLog_Lable_DurationColumn: "通话时长",
    Chat_TabName_Chat: "聊天",
    Chat_Button_Send: "发送",
    Chat_ToolTip_EnterToSend: "按[Enter] 发送",
    Sms_ToolTip_Delete: "删除",
    Contact_Label_Name: "姓名",
    Contact_Label_Group: "群组",
    Contact_Label_Search: "搜索",
    Contact_Label_WorkPhone: "工作",
    Contact_Label_WorkFax: "工作传真",
    Contact_Label_OtherPhone: "其他",
    Contact_Label_Note: "备注",
    Contact_Button_Save: "保存",
    Message_PhoneSelected: "已选",
    ToolTip_ClickToChat: "开始短信聊天",
    Message_DeleteCurrentChatFailure: "无法删除选定的内容。",
    Message_CreateContactInfo: "此联系人没有电话号码，是否要编辑？",
    Message_DeleteMessageFailure: "删除此信息失败。",
    Message_NotAllLoaded: "载入该组联系人失败。",
    Message_SureToDeleteCallLogs: "您确定要删除所选的通话记录吗？",
    Message_NotAllCallLogDeleted: "出现错误！只有部分选定的电话记录被删除。",
    ToolTip_DeleteCallLog: "删除此通话记录",
    ToolTip_CreateContactInfo: "创建新联系人",
    Message_LoadingThreadListFailure: "加载短信列表失败。",
    Message_NotAllThreadDeleted: "错误！所选内容未能全部删除。",
    Message_LoadingGroupContactsFailure: "未能加载群组联系人",
    Contact_Lable_NumberColumn: "号码",
    Message_SendFailBecauseOfARConn: "与设备通信时出错。",
    Confirm_ReSendThisSMS: "是否确定要重新发送此信息？",
    Message_SendFailBecauseOfRErrId: "发送信息失败！请在您的设备上检查信息是否发送成功。",
    Message_CreateChatWindowError: "加载时出错。",
    Message_SendFailBecauseOfDataErr: "错误！信息未能发送。",
    ToolTip_PleaseWait: "请稍候...",
    Count_Contacts: "{0} 位联系人",
    Cut_Fail: "剪切失败",
    CallogTab_All: "全部",
    CallogTab_Incoming: "来电",
    CallogTab_Outgoing: "呼出",
    CallogTab_Missed: "未接来电",
    Message_CanNotDeleteContact: "加载时无法编辑联系人。",
    Message_ReadSmsError: "未能加载新信息。",
    CallLog_Lable_NameColumn: "姓名",
    CallLog_Lable_NumberColumn: "号码",
    Chat_TabName_ContactInfo: "联系人信息",
    Chat_TabName_CallLog: "通话记录",
    Chat_ToolTip_EnterCtrlToSend: "按 [Ctrl+Enter] 发送",
    Contact_Label_Phone: "号码",
    Contact_Label_MobilePhone: "手机",
    Contact_Label_HomePhone: "家庭",
    Contact_Label_HomeFax: "家庭传真",
    Contact_Button_Create: "创建",
    Sms_Button_SelectContact: "联系人",
    Lable_SmsTo: "收件人",
    Message_SureToDeleteMessage: "确定要删除此信息吗？",
    Message_ReveivedMessage: "从 {0} 处收到 {1} 条消息",
    Message_LoadingSMSFailure: "载入短信列表失败。",
    Contact_Lable_NameColumn: "姓名",
    Message_InputContactSenseFailure: "没有匹配项",
    Message_NumberAndContentNeeded: "请填写电话号码和内容。",
    Message_ContactFormatErrorOrPositionErrorFromPasted: "格式无效或位置错误！",
    Button_NewContact: "新建联系人",
    Contact_all_numbers: "所有号码",
    ToolTip_NamesNumbersSeparateComma: "请输入联系人的姓名或电话，用逗号隔开。",
    Message_ConfirmToDeleteContact: "确定要删除联系人 {0}？",
    Message_SureToDeleteThisThread: "您确定要删除此内容吗？",
    Message_StarFieldIsNeeded: "加星（*）项必须填写",
    ToolTip_RequirePermission: "请在设备上开启Airdroid发送短信的权限。",
    Contact_all: "所有联系人"
}, Airdroid.Lang.Upload = {
    Button_SelectFolder: "选择目录",
    Message_SuportFileTypes: "支持的文件格式：{0}",
    Msg_not_avail: "上传失败。SD卡可用空间不足。",
    Message_SureToStopUploadFiles: "关闭将停止上传。您确定要关闭窗口吗？",
    Label_FileTypesDesc: "选择文件",
    Lable_InstallApps: "安装应用程序",
    Label_PhotoTypesDesc: "选择照片",
    Label_MusicTypesDesc: "选择音乐",
    Label_RingtoneTypesDesc: "选择铃声",
    WindowTitle_ImportRingtones: "上传铃声",
    WindowTitle_ImportMusic: "上传音乐",
    WindowTitle_ImportPhotos: "上传照片",
    WindowTitle_ImportFiles: "上传文件",
    Label_UPloadSucceed: "成功",
    Label_UploadFailure: "失败",
    notsupportdragfolders: "当前浏览器不支持拖拽文件夹",
    OnlySupportChrome: "文件夹上传功能仅支持Chrome浏览器。",
    FileDropTip: "将要上传的文件或文件夹拖放到此处",
    ApkDropTip: "将应用程序拖拽到这里安装",
    Tip_UploadTo: "目标文件夹：{0}",
    Msg_File_TooLarge: "文件大小超过您的 web 浏览器的限制。",
    DataFlowNotAbleToUpload: "您本月的远程连接模式流量配额已用完，本月内您不能再使用远程连接模式传输文件。",
    Label_ProgressColumn: "进度",
    Button_SelectFiles: "选择文件",
    Button_ClearSucceed: "清除已上传内容",
    ToolTip_ClearSucceed: "清除上传的文件",
    Label_ApkSucceedTip: "成功。请在设备上继续操作。",
    Label_UPloadCanced: "已取消",
    Label_UploadWaiting: "等待中",
    NameExistSureRename: "文件夹 {0} 已经存在。重命名为 {1} 吗？",
    RemoteMode_FileTooLarge: "远程连接模式中单个文件的大小不能超过 {0} MB 。若要传输较大的文件，请在同一网络中使用 AirDroid。"
}, Airdroid.Lang.Applications = {
    Message_Uninstalling: "正在卸载...",
    Message_UninstallError: "应用程序未安装或已卸载。",
    Message_InstallingApp: "正在安装 [{0}]...",
    Message_UninstallApp: "正在卸载 [{0}]...",
    Message_SureToUninstallSelectedApp: "卸载所选 {0} 个应用程序吗？",
    Message_Uploading: "上传中...",
    TabName_UserApp: "用户",
    Button_InstallApp: "安装应用程序",
    Message_TapOnDevice: "在设备上点击",
    Button_InstallUnknownSourceAppGuide: "用户指南",
    ToolTip_InstallUnknownSourceApp: "要允许非市场的应用程序的安装，请到设备的设置中开启允许安装未知来源程序。",
    Message_LoadAppListError: "加载应用列表失败。",
    Message_ConfirmToUninstallApp: "确定要卸载 {0}？",
    Message_UploadingError: "上传 {0} 时出现错误。",
    Message_InstallingAppError: "安装时出现错误。{0}操作中止。",
    Message_ActionDone: "确定",
    Message_NOfAppsProhibited: "禁止复制以下 {0} 个应用程序。",
    Message_AppProhibitedTip: "开发者启用了复制保护，防止应用程序从设备中被复制。",
    Label_InstallTip: "请在设备上完成操作",
    Message_ReinstallStartSuc: "已启动重新安装",
    Suffix_InstallInQueue: "队列",
    ZipName_AppDefaultExportName: "Apps_downloaded_by_AirDroid",
    Message_SelectApp: ".apk",
    Message_UninstallSucceed: "卸载成功",
    TabName_SystemApp: "系统",
    TabName_Recommends: "推荐应用",
    Button_UninstallApp: "卸载",
    Label_InstalledDateColumn: "安装日期"
}, Airdroid.Lang.BrowserTip = {
    BrowserTip1: "{0}我们一直在努力提升 AirDroid 在各种浏览器中的性能。{1}{2}为获得最佳的体验，我们强烈建议您使用{3}{4}以下任意一款我们推荐的浏览器。{5}",
    BrowserTip2: "对其他浏览器的支持正在实验阶段。",
    BrowserGo: "继续使用当前浏览器。>>"
}, Airdroid.Lang.Filemanage = {
    Message_FileItemMore: "您选择了超过250个的文件，这需要较长的加载时间，是否继续？",
    Msg_NOSdCard: "SD卡未找到。",
    Msg_LoadFileTreeError: "加载文件夹目录失败。",
    ZipName_FileDefaultExportName: "Files_downloaded_by_AirDroid",
    Message_FileExist: "文件夹名 {0} 已存在。请使用另一个名称。",
    Message_SureToDeleteFile: "确定删除此文件吗？",
    Message_SureToDeleteSelectedFiles: "确定删除选中的 {0} 个文件吗？",
    Message_ListFolderFailure: "未能加载文件夹 {0}。",
    Message_RenameFailure: "无法重命名 {0}。",
    Message_SelectNoFiles: "没有选定的文件。",
    Label_NewFolderName: "文件夹名称",
    Message_FileHasIllegalCharacter: '文件名不能包含以下字符：   / : * ? " < > , | &',
    Message_CreateFolderFailure: "未能创建文件夹 {0}。",
    FileName_tooLong: "文件名必须在 {0} 个字符内。",
    Message_FileNameExist: "文件名称重复",
    MenuItem_Move: "移动",
    Message_FolderSummary: "{0}个条目",
    ExternalSD_Directory: "外部SD卡",
    SDCard_Directory: "SD卡",
    SystemDirectoryWarn1: "警告",
    CreateShortcut: "创建桌面快捷方式",
    Message_CopyOrCutSucceed: "{0} 文件成功。",
    Label_NewName: "新名称",
    Message_SameFileName: "文件名没有更改。",
    Message_FileNameIsNull: "文件名不能为空。",
    ToolTip_SelectedFiles: "已选择 {0} 个条目",
    Message_CopySelfError: "目标文件夹是源文件夹的子文件夹。",
    System_Directory: "系统",
    SystemDirectoryWarn2: "修改或删除系统文件可能导致您的手机变砖,请小心操作。",
    SystemDirectoryWarn3: "因权限问题，您对某些系统文件的操作可能会失败。",
    Action_Permission_Denied: "操作失败，没有权限对SD卡进行该操作。"
}, Airdroid.Lang.Hotkeys = {
    Lbl_ctrl_v: "粘贴",
    Lbl_ctrl_c: "复制",
    Lbl_ctrl_a: "全选",
    Lbl_f2: "重命名",
    Btn_Hotkeys: "快捷键:",
    Lbl_HotkeysList: "快捷键:",
    Lbl_ctrl_x: "剪切",
    Lbl_delete: "删除"
}, Airdroid.Lang.Summary = {
    Coming_soon: "即将推出",
    Label_Music: "音乐",
    Label_Videos: "视频",
    Label_Photos: "照片",
    Label_Contacts: "联系人",
    Label_Messages: "信息",
    Label_InternalStorage: "内部存储器 (可用： {0})",
    Label_SDStorage: "SD 卡 (可用： {0})",
    Message_ReadAndroidSummaryError: "错误。",
    Button_SummaryDetail: "详细信息",
    Label_Other: "其他",
    Label_Apps: "应用程序",
    Label_eBooks: "图书",
    Title_InternalStorage: "内部存储",
    Title_SDStorage: "SD卡",
    Title_exSDStorage: "外置SD卡",
    Label_exSDStorage: "外置SD卡(可用：{0})"
}, Airdroid.Lang.Modules = {
    SummaryDetail: "概述",
    Messages: "消息",
    Apps: "应用程序",
    Files: "文件",
    Music: "音乐",
    Contacts: "联系人",
    CallLog: "通话记录",
    NewContact: "新建联系人",
    upload: "上传文件",
    WebBrowser: "浏览器",
    EditContact: "编辑联系人",
    Chat: "聊天",
    NewMessage: "新建信息",
    SelectContacts: "选择联系人",
    Video: "视频",
    Recommends: "推荐",
    MessageSettings: "信息设置",
    Installapps: "安装应用程序",
    quickupload: "上传文件",
    Screenshot: "屏幕截图",
    Camera: "相机",
    Photos: "照片",
    Ringtones: "铃声",
    VideoPlayer: "视频播放器",
    AudioPlayer: "音频播放器",
    FrequentContacts: "常用联系人",
    Quixey: "Quixey",
    Settings: "设置",
    FindPhone: "寻找手机",
    Language: "语言",
    UserCenter: "帐户中心",
    Increase_Quota: "增加流量",
    Premium: "高级帐户",
    ContactCut: "裁剪图片",
    Lab: "实验室",
    Gift: "领取礼包",
    FeedBack: "反馈",
    Help: "帮助",
    Add: "添加",
    DesktopContact: "联系人快捷方式",
    DesktopFileList: "文件夹快捷方式"
}, Airdroid.Lang.Video = {
    VideoCategory_Camera: "相机",
    VideoCategory_Others: "其他",
    Btn_PlayAnyway: "仍继续播放",
    Tip_FormatNotSupported: "不支持该视频格式。您可以尝试下载到电脑后，用播放器播放。",
    Message_ReadVideoListError: "加载视频列表时出现错误。",
    Message_DeleteFail: "删除视频时出错。",
    Message_DeleteSuc: "删除成功。",
    Confirm_DeleteSingleVideo: "确实要删除这个视频吗？",
    Confirm_DeleteMultiVideos: "确实要删除所选的视频吗？",
    Confirm_DeleteAllVideos: "确实要删除所有视频吗？",
    Message_StreamNotFound: "未找到流。",
    Message_NoSupportThisType: "不支持此视频格式。",
    Tip_VideoTooLarge: "此视频大小超过100MB，建议您下载后播放。",
    Tip_CannnotPlay: "无法播放该视频。您可以尝试下载到电脑后，用播放器播放。",
    Message_VideoPlayerError: "播放器错误。",
    Message_ReadVideoSummaryError: "加载视频摘要时出错。",
    CategoryCountSuffix_Items: "条目",
    Tip_QuickTime_Installation_1: "请根据浏览器的提示或是 <a target='_blank' href='{0}'>点击下载 QuickTime </a> 来观看此视频.",
    Tip_QuickTime_Installation_2: "请在安装后重新启动浏览器。"
}, Airdroid.Lang.Screenshot = {
    Tip_GrantRootPerm: "如果您的 Android 设备中没有出现提示信息，请转到您的权限管理程序（如{0}）手动授予 AirDroid 超级用户权限。",
    RootTip_Root_Q_1: "什么是超级用户权限？如何获取超级用户权限？",
    RootTip_Root_Q_2: "如何授予 AirDroid 所需要的超级用户权限？",
    RootTip_Root_A_2_2: "当您获取 Android 设备的超级用户权限后，打开 AirDroid 并再次尝试屏幕截图功能。您可以实时查看 Android 屏幕上的内容。",
    RootTip_Root_Q_3: "为什么 AirDroid 需要超级用户权限来获取屏幕截图？",
    Tip_AllowRootPerm: "如果您的设备已经获取超级用户权限，请在您的 Android 设备上点击允许来赋予 AirDroid 所需要的权限：",
    Tip_NotPerm: "您的设备可能未 ROOT。AirDroid 需要 ROOT 权限才能查看和获取屏幕截图。",
    Tip_GettingRootPerm: "AirDroid 试图获得超级用户权限以查看并捕获屏幕截图。",
    Tip_screenshot: "捕获屏幕截图",
    Tip_play: "实时桌面",
    Tip_stop: "停止实时桌面",
    Tip_fullscreen: "全屏",
    RootTip_Root_A_3: "要进行屏幕截图，AirDroid 需要访问您 Android 的系统级接口。",
    RootTip_Root_Q_4: "屏幕截图功能会影响我的 Android 系统吗？",
    RootTip_Root_A_4: "不会。AirDroid 在捕获屏幕截图时将只执行读取操作。",
    tip: "按[F11]键进入全屏模式，按[ESC]键退出。",
    Msg_NotPerm: "需要 ROOT 权限",
    Tip_networkspeed: "您的网速较慢。",
    RootTip_Root_A_1: "获取超级用户权限是允许运行 Android 系统的手机、平板电脑和其他设备的用户获得对 Android 系统特殊权限（也称为“超级用户访问权限”）的过程。{0}了解更多{1}"
}, Airdroid.Lang.Desktop = {
    MenuItem_CloseAll: "关闭全部窗口",
    MenuItem_Restore: "还原窗口",
    MenuItem_ShowDesktop: "显示桌面",
    MenuItem_Close: "关闭",
    MenuItem_Min: "最小化",
    MenuItem_Max: "最大化",
    No_Frequent_Contacts: "无内容",
    LanConnectMode: "本地连接模式",
    RemoteConnectMode: "远程连接模式",
    LiteConnectMode: "您现在使用的是简版连接模式。要享受完整版的 AirDroid 给您带来的无线体验，请访问 {0}web.airdroid.com{1}",
    MenuItem_Lock: "锁定",
    Failed_To_Save: "保存失败"
}, Airdroid.Lang.AudioPlayer = {
    Btn_Prev: "上一首",
    Btn_Next: "下一首",
    Btn_Play: "播放",
    Btn_Pause: "暂停",
    Btn_Unmute: "取消静音",
    MI_RepeatOne: "单曲循环",
    MI_LoopOn: "列表循环",
    NotSupportError: "错误",
    TypeNotSupport: "不支持的文件类型。",
    Btn_Mute: "静音",
    MI_LoopOff: "顺序播放",
    SupportDesc: "未能加载播放器。请尝试安装 Flash 插件。"
}, Airdroid.Lang.Workspace = {
    LeftBar_More_MenuItem_Lock: "锁定",
    Message_ClearAllNotice: "清除所有通知。"
}, Airdroid.Lang.Photo = {
    ZipName_PhotoDefaultExportName: "Photos_downloaded_by_AirDroid",
    Message_SureToSetAsWallpaper: "确定要将此图片设为壁纸吗？",
    Message_SetWallpaperSucceed: "壁纸设置成功。",
    Message_SureToDeleteThisPhoto: "确定要删除此照片吗？",
    Message_DeleteThisPhotoFailure: "未能删除此照片。",
    Label_CameraFolder: "相机胶卷",
    Label_WallpaperFolder: "壁纸",
    Message_SureToDeleteSelectedPhoto: "确定要删除所选的照片吗？",
    Message_DeleteSelectedPhotoFailure: "未能删除选中的照片。",
    Last_Tip: "已是最后一张照片。如果您继续，将返回到第一张。"
}, Airdroid.Lang.Music = {
    ZipName_MusicDefaultExportName: "Music_downloaded_by_AirDroid",
    Label_Artist: "艺术家",
    ToolTip_AlbumName: "专辑:",
    ToolTip_AlbumArtist: "艺术家:",
    ToolTip_SortBySongs: "列表视图",
    ToolTip_SortByAlbums: "网格视图",
    MenuItem_SetAsPhoneRingtone: "电话铃声",
    MenuItem_SetAsNotification: "通知铃声",
    MenuItem_SetAsAlarm: "闹铃铃声",
    Message_SureToDeleteThisSong: "确定要删除此首歌曲吗？",
    Message_DeleteSongFailure: "不能删除。",
    Message_SureToDeleteSelectedSongs: "是否确定要删除所选的歌曲吗？",
    Message_DeleteSongsFailure: "无法删除选定的歌曲。",
    Message_AlreadyPhoneRongtone: "此首歌曲已被设为电话铃声。",
    Message_AlreadyNotification: "此首歌曲已被设为通知铃声。",
    Message_AlreadyAlarm: "此首歌曲已被设为闹铃铃声。",
    Message_SetPhoneRongtineFailure: "未能设置新电话铃声。",
    Message_SetNotificationFailure: "新提示声设置失败。",
    Label_Album: "专辑",
    ToolTip_AlbumTracks: "音轨：",
    MenuItem_SetAs: "设为",
    Message_SetPhoneRongtineSucceed: "新电话铃声已设置。",
    Message_SetNotificationSucceed: "新通知铃声已设置。",
    Message_SetAlarmSucceed: "新闹铃铃声已设置。",
    Message_SetAlarmFailure: "未能设置为闹铃铃声。"
}, Airdroid.Lang.Ringtone = {
    TabName_Notification: "通知",
    TabName_Alarm: "闹铃",
    ZipName_RingtoneDefaultExportName: "Ringtone_downloaded_by_AirDroid",
    Message_RingtoneInUse: "此铃音正在被使用。",
    Message_SureToDeleteRingtone: "确定要删除此铃声吗？",
    Message_SureToDeleteSelectedRingtones: "确定要删除所选铃音吗？",
    Message_DeleteRingtoneFailure: "未能删除此铃声。",
    TabName_Ringtone: "电话",
    Button_Set: "设置",
    Message_CanNotDelete: "不能删除系统铃声。"
}, Airdroid.Lang.Clipboard = {
    Message_ReadClipFromDeviceFailure: "无法获取设备中的剪辑。",
    Message_SendClipToDeviceFailure: "无法将剪贴板中的内容发送到设备。",
    Message_SendToDeviceClipBoardSucceed: "保存至设备的剪贴板。",
    Button_ToDevice: "刷新",
    Button_FromDevice: "保存",
    Message_ContentTooLong: "错误！内容过长。{0}超过 {1} 个字符。",
    Input_PlaceHolder: "剪贴板"
}, Airdroid.Lang.TitleWidget = {
    Message_ReceivedMessages: "收到{0}条新消息 "
}, Airdroid.Lang.About = {
    Label_Website: "<a target='_blank' tabname='AirDroid' href='http://www.airdroid.com'> http://www.airdroid.com</a>",
    Label_Help: "<a target='_blank' tabname='User Guide' href='http://www.airdroid.com/userguide.html'> http://www.airdroid.com/userguide.html</a>",
    Url_Facebook: "http://www.facebook.com/AirDroid",
    Url_Twitter: "http://Twitter.com/AirDroidTeam",
    Url_Youtube: "http://www.youtube.com/user/AirDroidTeam",
    Url_Tumblr: "http://airdroid.tumblr.com/",
    Url_Googleplus: "http://gplus.to/AirDroid",
    Label_Copyright: "© 2014 Sand Studio",
    VScrollText_Main: "AirDroid是一个快速、免费的应用，以无线方式通过网页浏览器管理您的Android设备。<br/><br/>感谢来自以下朋友的建议和帮助：<br/>Ramona Shelburne（美国）<br>John Phillips（英国）<br>Turkdale（土耳其）<br>Peter Yang（中国）<br>Anna Ringstrom (法国）<br> Amy Norton（德国）<br>Salynn Boyles（美国）"
}, Airdroid.Lang.Battery = {
    Message_GettingLow: "电池电量低:",
    Message_Reminding: "或更少的剩余。",
    Message_ConnectCharge: "请连接充电器"
}, Airdroid.Lang.SMSTimeOffsetSetting = {
    Label_QuestionTitle: "调整传入消息的时间戳",
    Label_Explain: "偏移量 = 正确的时间戳-错误的时间戳",
    Select_MinSuffix: "分钟",
    Select_HourSuffix: "小时",
    ButtonText_Save: "保存",
    MsgBox_SaveFailed: "保存失败。请重试。",
    MsgBox_Saved: "已保存, 正在刷新",
    Label_Value: "时间偏移调整"
}, Airdroid.Lang.Transport = {
    Main_Button_OpenInDevice: "在设备上打开",
    OpacityTip_OpenURLSuccess: "打开成功。请在设备上检查。",
    OpacityTip_OpenURLFail: "在设备上打开时出错。请重试。"
}, Airdroid.Lang.Browser = {
    ToolTip_Back: "后退",
    ToolTip_AddTab: "新的选项卡",
    TabName_UserGuide: "用户指南",
    TabName_Facebook: "Facebook",
    TabName_Twitter: "Twitter",
    TabName_TeamBlog: "博客",
    TabURL_AppUserGuide: "http://www.airdroid.com/userguide.html?name=apps",
    TabURL_SMSUserGuide: "http://www.airdroid.com/sms.html",
    TabName_NewTab: "新的选项卡",
    ToolTip_Forward: "前进",
    ToolTip_ListAllTabs: "所有选项卡"
}, Airdroid.Lang.Camera = {
    underDevTip: "该功能目前正在开发中，即将推出，请过段时间再来看看哦~",
    tip: "按 [F11] 进入全屏模式，按 [ESC] 退出。",
    Tip_stop: "停止实时桌面",
    Tip_Photo: "拍照",
    Tip_networkspeed: "您的网络当前过慢",
    Tip_StopError: "关闭相机失败",
    Tip_fullscreen: "全屏",
    Tip_reStart: "您的相机可能已崩溃。{0}请尝试重启{1}",
    Tip_StartError: "启动相机失败",
    Tip_play: "实时桌面"
}, Airdroid.Lang.FindMyPhone = {
    Custom_Phone: "{0} 的电话",
    Location_Time: "{0} 分钟前的位置",
    Location_Date: "定位时间: {0}",
    location_load: "正在定位设备",
    Send_Pre: "此设备丢失，请与我联系。",
    Send_Tip: "输入一条消息，它将与您的电话号码一起显示在您的设备上。",
    Send_Default: "警告",
    Button_Cancel: "取消",
    Button_Confirm: "确认",
    Enter_Pwd_Error: "密码不匹配。",
    Wipe_Title: "擦除设备",
    Wipe_Tip_Warning: "警告：您的设备将被恢复为出厂设置！所有个人数据将被删除，且无法恢复！",
    Button_Continue: "继续",
    Wipe_Sure_Tip: "擦除设备",
    Wipe_Pre: "输入AirDroid密码",
    Wipe_Data: "正在擦除数据...",
    Confirm_Content: "输入AirDroid密码",
    Confirm_Required: "输入AirDroid密码",
    Confirm_Error: "密码不正确。",
    Error_Code_Offline: "目前无法访问您的Android设备。",
    Error_Code_Send_Fail: "发送消息失败。",
    Error_Code_Wipe_Fail: "无法擦除设备上的数据。",
    Mask_Tip2: "请在您的设备上的 AirDroid 设置项中启用此功能，然后点击{0}刷新{1}。",
    Login_Title: "需要重新登录",
    Phone_Tip: "单击以显示操作",
    CAPS_Lock: "大写锁写已打开",
    Device_Offline: "目前无法访问您的Android设备。",
    My_Device: "我的设备",
    Send_loading: "正在设置锁屏密码...",
    Button_Send: "发送",
    Enter_Pwd: "设定密码",
    ReEnter_Pwd: "确认密码",
    Wipe_Tip: "此操作会将您的设备恢复为出厂设置，所有个人数据将被永久删除，且不能恢复。确定要执行此操作吗？",
    Button_Wipe: "擦除",
    Confirm_Title: "警告",
    Error_Code_Lock_Fail: "锁定设备失败。",
    Mask_Tip1: "设备上的查找手机功能未开启。",
    Login: "登录",
    Not_Find: "无法定位到该设备。",
    Airdroid_Password: "AirDroid密码",
    Standard: "标准",
    Satellite: "卫星",
    Load_Wrong_Tip1: "哎呀......出错了。",
    Load_Wrong_Tip2: "点击{0}此处{1}以重试。",
    Low_Version_Tip: "寻找手机不支持系统版本小于2.1的设备",
    Hybrid: "混合"
}, Airdroid.Lang.DialPad = {
    Call_Out_Tip: "请在设备上操作。",
    Button_Call: "呼叫",
    Button_Message: "消息",
    Add_Contact: "添加到联系人",
    Call_Ring_Title: "电话呼入",
    Call_Reject: "拒绝",
    Call_Reject_Send: "发短信拒绝",
    Call_Out: "通话中",
    Call_Out_End: "结束通话",
    Call_Notice: "{0} 未接电话",
    Call_Answer: "已连接"
}, Airdroid.Lang.AirTransport = {
    OpacityTip_OpenURLFail: "在设备上打开失败。请重试。",
    Message_ContentTooLong: "错误！内容过长，{0}超过 {1} 个字符。",
    Input_PlaceHolder: "剪贴板",
    Url: "网址",
    Main_Button_OpenInDevice: "在设备上打开",
    OpacityTip_OpenURLSuccess: "打开成功。请检查设备。",
    Message_ReadClipFromDeviceFailure: "从设备中读取剪切内容失败。",
    Message_SendClipToDeviceFailure: "无法将剪贴板中的内容发送到设备。",
    Button_ToDevice: "刷新",
    Button_FromDevice: "保存",
    File: "文件",
    Clipboard: "剪贴板",
    Drag_Files: "拖放文件或文件夹到此处",
    clear: "清除",
    Proceed_Device: "请在设备上完成操作",
    Upload_Success: "{0} 成功",
    Upload_Faile: "{0} 失败，{1} 成功",
    Message_SendToDeviceClipBoardSucceed: "保存至设备的剪贴板。",
    Select_File: "选择文件",
    App: "应用",
    Update_To: "上传到"
}, Airdroid.Lang.Welcome = {
    t1: "省一条线缆",
    t2: "摆脱数据线，直接通过浏览器管理您的手机，即使手机不在身边。",
    t3: "省一块屏幕",
    t5: "省一份担心",
    t6: "手机丢失时，定位并锁定它；无法拿回吗？简单操作即可帮您擦除手机上的隐私数据。",
    t9: "免费体验高级功能",
    t10: "您已经成功升级为 AirDroid 2 高级帐户",
    t11: "您已免费获得 2 个月的 AirDroid 2 高级会员资格，可以享受 AirDroid 2 的所有服务 :-)",
    share_on: "分享到 {0}",
    share_cnt: "我发现了一个非常好用的免费应用程序AirDroid 2，无需数据线，通过电脑的浏览器来管理Android设备： {0}",
    t14: "超大远程流量",
    t19: "远程连接时控制设备的照相机",
    t20: "远程拨打电话",
    t21: "远程连接时，可通过web.airdroid.com控制手机拨打电话",
    t22: "无广告",
    t23: "升级为高级用户，可以隐藏AirDroid中的促销信息",
    t25: "一个帐户最多可以绑定6台Android设备",
    t28: "升级为高级帐户",
    t4: "通过电脑收发短信，不受手机小屏幕的限制，高效便捷。",
    t7: "免费升级为 AirDroid 2 高级用户！",
    t8: "在 Facebook 或 Twitter 上分享 AirDroid 2 就免费获得 2 个月高级会员。这是限时的优惠噢！",
    t12: "立即体验高级功能",
    t13: "发送失败，请重试。",
    t16: "更大远程文件",
    t17: "远程连接时上传单个文件大小提升至100MB",
    t18: "远程照相机",
    t24: "支持多设备",
    t26: "优先服务",
    t27: "高级用户可以优先获得技术支持",
    t29: "寻找手机",
    t30: "拍下入侵者的照片；移动设备可使用:f.airdroid.com",
    t15: "每月远程数据流量提升至1GB"
}, Airdroid.UsedLang = Airdroid.Lang;
